Repository projectcalico/felix, pull requests merged in 2018-03, with the labels that each got.

#1718 Whitelist failsafe port response traffic in the raw table only
  fv/donottrack_test.go
  fv/workload/workload.go
  rules/static.go
  rules/static_test.go
Labels: release-note-required

#1747 Merge pull request #1726 from nwoodmsft/master
  dataplane/windows/endpoint_mgr.go
  dataplane/windows/policysets/policyset_defs.go
  dataplane/windows/policysets/policysets.go
Labels: kind/bug

#1736 Run HostEndpoint tests against KDD also
  fv/config_update_test.go
  fv/containers/containers.go
  fv/donottrack_test.go
  fv/etcd_restart_test.go
  fv/fv_suite_test.go
  fv/health_test.go
  fv/host_port_test.go
  fv/infrastructure/datastore_describe.go
  fv/infrastructure/etcd.go
  fv/infrastructure/felix.go
  fv/infrastructure/infra_etcd.go
  fv/infrastructure/infra_k8s.go
  fv/infrastructure/infrastructure.go
  fv/infrastructure/topology.go
  fv/ingress_egress_test.go
  fv/ipip_test.go
  fv/k8sapiserver/k8sapiserver.go
  fv/latency_test.go
  fv/named_ports_test.go
  fv/netsets_test.go
  fv/policysync_test.go
  fv/pre_dnat_test.go
  fv/test-workload/test-workload.go
  fv/utils/utils.go
  fv/workload/workload.go
Labels: cherry-pick-candidate
