Repository projectcalico/felix, pull requests merged in 2019-10, with the labels that each got.

#2152 need to harden go mod downloads against network errors
  Makefile
Labels: docs-not-required, release-note-not-required

#2155 Add makefile target to update libcalico pin
  Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2159 Token projection support
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2160 Update go.sum
  go.sum
Labels: docs-pr-required, release-note-required

#2156 [release-v3.10] Automatic update of libcalico-go to 399044ecb65942961586f38c38415d95b9122dcc
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2164 Use master Typha for FV, not some ancient pin!
  Makefile
  fv/infrastructure/typha.go
Labels: docs-pr-required, release-note-required

#2162 Fix memory leak in endpoint_mgr
  intdataplane/endpoint_mgr.go
Labels: docs-not-required, release-note-required

#2165 Implementing backoff for XDP failures and eliminate panic behaviour for non-xdp non-responding kernels
  dataplane/linux/int_dataplane.go
  dataplane/linux/xdp_state.go
  dataplane/linux/xdp_state_test.go
Labels: docs-not-required, release-note-required

#2168 Remove 'undo' behavior from local_build
  Makefile
Labels: docs-not-required, release-note-not-required
