Repository projectcalico/felix, pull requests merged in 2019-11, with the labels that each got.

#2167 Handle multiple workload endpoints with the same interface name
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/endpoint_mgr_test.go
Labels: docs-not-required, release-note-required

#2170 [release-v3.10] Automatic patch of libcalico-go to 8f81e1e344ce1dc436b066ea242e4da5df765a97
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2171 Add profiles to networkset for label inheritance
  go.mod
  go.sum
  labelindex/named_port_index.go
  labelindex/named_port_index_test.go
Labels: docs-not-required, release-note-not-required

#2172 [release-v3.9] Automatic patch of libcalico-go to 1891db7ae73bcafe01c90943f5eaac25ec53c96d
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2173 Allow ipV6LinkLocalCIDR route to be programmed other than by us
  routetable/route_table.go
  routetable/route_table_test.go
Labels: docs-not-required, release-note-not-required

#2174 Allow ipV6LinkLocalCIDR route to be programmed other than by us
  routetable/route_table.go
  routetable/route_table_test.go
Labels: docs-not-required, release-note-not-required

#2175 Allow ipV6LinkLocalCIDR route to be programmed other than by us
  routetable/route_table.go
  routetable/route_table_test.go
Labels: docs-pr-required, release-note-required

#2176 Fix unnamed field initialization
  labelindex/named_port_index_test.go
Labels: docs-pr-required, release-note-required

#2179 Fix that Typha was failing to start in k8sfv tests.
  k8sfv/calc_graph_test.go
  k8sfv/k8sfv.go
  k8sfv/k8sfv_suite_test.go
  k8sfv/leastsquares_test.go
  k8sfv/metric.go
  k8sfv/namespace.go
  k8sfv/pod.go
  k8sfv/run-test
  k8sfv/scale_test.go
Labels: docs-pr-required, release-note-required

#2181 Don't wait for test containers to gracefully shut down.
  fv/containers/containers.go
Labels: docs-pr-required, release-note-required

#2182 Disable node CIDR allocation and defer cleanup
  fv/infrastructure/infra_k8s.go
Labels: docs-not-required, release-note-not-required

#2183 Fix incremental builds. Avoid depending on phony targtets.
  Makefile
Labels: docs-not-required, release-note-not-required

#2178 Move common Makefile targets to Makefile.common
  Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2185 Switch Makefile.common from wget to curl, remove wget dependency
  Makefile
Labels: docs-not-required, release-note-not-required

#2186 make update-pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2187 Move image build/push targets back to local Makefile
  Makefile
Labels: docs-not-required, release-note-not-required
