Repository projectcalico/felix, pull requests merged in 2019-07, with the labels that each got.

#2071 Better VXLAN diags on interface creation failure
  dataplane/linux/vxlan_mgr.go
Labels: docs-not-required, release-note-not-required

#2070 Add support for iptables 1.8
  config/config_params.go
  dataplane/driver.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/int_dataplane_test.go
  docker-image/Dockerfile.amd64
  fv/health_test.go
  glide.lock
  glide.yaml
  iptables/features_detect_test.go
  iptables/restore_buffer.go
  iptables/rules.go
  iptables/rules_test.go
  iptables/table.go
  iptables/table_test.go
  iptables/utils_for_test.go
Labels: docs-pr-required, hold-merge, release-note-required

#2074 [v3.8] Add support for iptables 1.8
  config/config_params.go
  dataplane/driver.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/int_dataplane_test.go
  docker-image/Dockerfile.amd64
  fv/health_test.go
  glide.lock
  glide.yaml
  iptables/features_detect_test.go
  iptables/restore_buffer.go
  iptables/rules.go
  iptables/rules_test.go
  iptables/table.go
  iptables/table_test.go
  iptables/utils_for_test.go
Labels: docs-pr-required, release-note-required

#2075 [release-v3.8] Automatic patch of libcalico-go to ac36d966132f2019eb4afc4d3823ed2a98564d2f
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#2080 Update go-build version
  Makefile
Labels: docs-not-required, release-note-not-required

#2081 Configurable prometheus host. Default value for prometheus host: empty
  config/config_params.go
  config/config_params_test.go
  daemon/daemon.go
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#2086 Fix nft mode failures due to u32 match
  dataplane/linux/endpoint_mgr_test.go
  iptables/match_builder.go
  rules/endpoints.go
  rules/endpoints_test.go
  rules/static.go
Labels: docs-not-required, release-note-not-required

#2087 Automated cherry pick of #2086: Fix nft mode failures due to u32 match
  dataplane/linux/endpoint_mgr_test.go
  iptables/match_builder.go
  rules/endpoints.go
  rules/endpoints_test.go
  rules/static.go
Labels: docs-not-required, release-note-required

#2093 Update pod2daemon binder version
  daemon/daemon.go
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required
