Repository projectcalico/felix, pull requests merged in 2019-04, with the labels that each got.

#1989 VXLAN calculation and data plane
  calc/async_calc_graph.go
  calc/calc_graph.go
  calc/calc_graph_fv_test.go
  calc/calc_graph_test.go
  calc/event_sequencer.go
  calc/vxlan_resolver.go
  config/config_params.go
  config/config_params_test.go
  dataplane/driver.go
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/endpoint_mgr_test.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/vxlan_mgr.go
  glide.lock
  glide.yaml
  ip/ip_addr.go
  proto/felixbackend.pb.go
  proto/felixbackend.proto
  routetable/route_table.go
  routetable/route_table_test.go
  rules/rule_defs.go
Labels: release-note-required

#1990 Don't police copyright in felixbackend.pb.go
  git-hooks/pre-commit-in-container
Labels: docs-not-required, release-note-not-required

#1991 Dataplane: optimize early host-endpoint blacklist rules
  .gitignore
  Makefile
  bpf/bpf-packr.go
  bpf/bpf.go
  bpf/bpf_test.go
  bpf/byteorder.go
  bpf/cmd/felix-xdp.go
  bpf/mock_bpf_lib.go
  bpf/packrd/packed-packr.go
  bpf/xdp/bpf.h
  bpf/xdp/filter.c
  check-licenses/check_licenses.go
  config/config_params.go
  dataplane/driver.go
  dataplane/linux/callbacks.go
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/endpoint_mgr_test.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/ipip_mgr.go
  dataplane/linux/ipsets_mgr.go
  dataplane/linux/ipsets_mgr_test.go
  dataplane/linux/mock_ipsets_for_test.go
  dataplane/linux/policy_mgr.go
  dataplane/linux/policy_mgr_test.go
  dataplane/linux/xdp_state.go
  dataplane/linux/xdp_state_test.go
  docker-build-images/bpf-clang-builder.Dockerfile.amd64
  docker-image/Dockerfile.amd64
  docker-image/Dockerfile.arm64
  docker-image/Dockerfile.ppc64le
  docker-image/Dockerfile.s390x
  fv/containers/containers.go
  fv/test-connection/test-connection.go
  fv/xdp_test.go
  git-hooks/files-to-skip
  git-hooks/pre-commit-in-container
  glide.lock
  glide.yaml
  ipsets/ipset_defs.go
  ipsets/ipsets.go
  iptables/feature_detect.go
  iptables/features_detect_test.go
  iptables/rules_test.go
  iptables/table_test.go
  iptables/utils_for_test.go
  versionparse/lib.go
Labels: docs-pr-required, release-note-required

#1992 Tweak VXLAN defaults and logging.
  calc/vxlan_resolver.go
  config/config_params.go
Labels: docs-pr-required, release-note-required

#1996 [master] Automatic update of libcalico-go to 727a39e77d674af6e7d6684b941916183d80f5de
  glide.lock
Labels: docs-pr-required, release-note-required

#1995 Add support for borrowed IPs to VXLAN
  calc/calc_graph_fv_test.go
  calc/resources_for_test.go
  calc/state_test.go
  calc/states_for_test.go
  calc/stats_collector_test.go
  calc/vxlan_resolver.go
  dataplane/mock/mock_dataplane.go
  glide.lock
  glide.yaml
  iptables/feature_detect.go
Labels: docs-completed, release-note-required

#1994 Add calc graph FVs for VXLAN processing.
  calc/calc_graph_fv_test.go
  calc/resources_for_test.go
  calc/state_test.go
  calc/states_for_test.go
  calc/vxlan_resolver.go
  dataplane/mock/mock_dataplane.go
Labels: docs-not-required, release-note-not-required

#1993 Fix vxlan device recreation
  dataplane/linux/vxlan_mgr.go
  fv/infrastructure/felix.go
  fv/infrastructure/infra_etcd.go
  fv/infrastructure/infra_k8s.go
  fv/infrastructure/infrastructure.go
  fv/infrastructure/topology.go
Labels: docs-not-required, release-note-not-required

#1999 docker-image: get bpftool from dockerhub
  docker-image/Dockerfile.amd64
  docker-image/Dockerfile.arm64
  docker-image/Dockerfile.ppc64le
Labels: docs-pr-required, release-note-required

#2001 Use calico fork of logrus
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#2000 Filter the source of VXLAN traffic to calico nodes only.
  dataplane/linux/int_dataplane.go
  dataplane/linux/vxlan_mgr.go
  fv/infrastructure/infra_k8s.go
  fv/infrastructure/topology.go
  fv/vxlan_test.go
  iptables/match_builder.go
  rules/rule_defs.go
  rules/static.go
Labels: docs-not-required, release-note-not-required

#2003 [master] Automatic patch of libcalico-go to 43c1da882b70aba9d0325e7de4393439ef202550
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#2002 Actually add FV tests for tunnel device
  fv/vxlan_test.go
Labels: docs-not-required, release-note-not-required

#2004 Delete the VXLAN device if VXLAN is disabled
  dataplane/linux/int_dataplane.go
  fv/vxlan_test.go
Labels: docs-not-required, release-note-not-required

#2005 Fix Felix readiness check when Typha is down at startup
  daemon/daemon.go
  fv/containers/containers.go
  fv/health_test.go
Labels: docs-not-required, kind/bug, priority/P1, release-note-not-required

#1998 Fix wrong tilde insertion in Debian package versions
  utils/lib.sh
Labels: docs-not-required, release-note-not-required

#2007 Fix tilde heuristic for initial 'v'
  utils/lib.sh
Labels: docs-pr-required, release-note-required

#2006 Updates for host-local IPAM
  daemon/daemon.go
  glide.lock
  glide.yaml
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#2011 [release-v3.6] Automatic patch of libcalico-go to 24a5a971c54bf0f43417bbfccd0b31e7ffa19a98
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#2009 Replicate tunnel masquerade rule for VXLAN.
  dataplane/driver.go
  rules/rule_defs.go
  rules/static.go
  rules/static_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#2012 Fix removing programs that have unallowed mode
  bpf/bpf.go
  bpf/bpf_test.go
  bpf/mock_bpf_lib.go
  dataplane/linux/xdp_state.go
  dataplane/linux/xdp_state_test.go
Labels: docs-pr-required, release-note-required

#2015 Fix removing programs that have unallowed mode (for v3.7)
  bpf/bpf.go
  bpf/bpf_test.go
  bpf/mock_bpf_lib.go
  dataplane/linux/xdp_state.go
  dataplane/linux/xdp_state_test.go
Labels: docs-pr-required, release-note-required

#2014 Merge pull request #2009 from fasaxc/vxlan-masq
  dataplane/driver.go
  rules/rule_defs.go
  rules/static.go
  rules/static_test.go
Labels: docs-not-required, release-note-not-required

#2010 Add extra VXLAN FVs.
  fv/containers/containers.go
  fv/vxlan_test.go
Labels: docs-not-required, release-note-not-required

#2013 [release-v3.5] Automatic patch of libcalico-go to aae6c757ef3745eb6ecb45351470e66c54fd9e13
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#2016 [release-v3.7] Automatic patch of libcalico-go to 6860ff2cfd923a870ff7a76563ce825d6e47adb8
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required
