Repository projectcalico/felix, pull requests merged in 2019-08, with the labels that each got.

#2037 Add support for setting the source hint on programmed device routes
  config/config_params.go
  dataplane/driver.go
  dataplane/linux/int_dataplane.go
  glide.lock
  glide.yaml
  routetable/route_table.go
  routetable/route_table_test.go
Labels: docs-pr-required, release-note-required

#2097 [master] Automatic update of libcalico-go to bf00054ed881fc4023e6e748c5faba3ad0757028
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#2098 Work around hpings' buggy RTT calculation.
  fv/workload/workload.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#2096 Adapt for github.com/projectcalico/packaging
  Makefile
  RELEASING.md
  debian/build-debs
  debian/copyright
  debian/rules
  docker-build-images/centos6-build.Dockerfile.amd64
  docker-build-images/centos7-build.Dockerfile.amd64
  docker-build-images/centos7-build.Dockerfile.ppc64le
  docker-build-images/install-centos-build-deps
  docker-build-images/install-ubuntu-build-deps
  docker-build-images/ubuntu-bionic-build.Dockerfile.amd64
  docker-build-images/ubuntu-bionic-build.Dockerfile.ppc64le
  docker-build-images/ubuntu-trusty-build.Dockerfile.amd64
  docker-build-images/ubuntu-trusty-build.Dockerfile.ppc64le
  docker-build-images/ubuntu-xenial-build.Dockerfile.amd64
  docker-build-images/ubuntu-xenial-build.Dockerfile.ppc64le
  rpm/build-rpms
  rpm/felix.spec.in
  utils/lib.sh
  utils/make-packages.sh
Labels: docs-pr-required, release-note-required

#2099 Code review markups for #2096
  Makefile
Labels: docs-pr-required, release-note-required

#2100 Update RELEASING.md for new packaging process
  RELEASING.md
Labels: docs-pr-required, release-note-required

#2088 Delete rules using full line instead of line number for non-cali chains
  iptables/rules.go
  iptables/rules_test.go
  iptables/table.go
  iptables/table_test.go
  iptables/utils_for_test.go
Labels: cherry-pick-candidate, docs-pr-required, release-note-required

#2105 Cherry-pick iptables race fix for v3.5
  iptables/rules.go
  iptables/rules_test.go
  iptables/table.go
  iptables/table_test.go
  iptables/utils_for_test.go
Labels: docs-pr-required, release-note-required

#2104 Cherry-pick iptables race fix for v3.6
  iptables/rules.go
  iptables/rules_test.go
  iptables/table.go
  iptables/table_test.go
  iptables/utils_for_test.go
Labels: docs-pr-required, release-note-required

#2103 Cherry-pick iptables race fix for v3.7
  iptables/rules.go
  iptables/rules_test.go
  iptables/table.go
  iptables/table_test.go
  iptables/utils_for_test.go
Labels: docs-pr-required, release-note-required

#2102 Cherry-pick iptables race fix for v3.8
  iptables/rules.go
  iptables/rules_test.go
  iptables/table.go
  iptables/table_test.go
  iptables/utils_for_test.go
Labels: docs-pr-required, release-note-required

#2090 switch felix to go modules
  Makefile
  calc/rule_convert_test.go
  calc/rule_scanner_test.go
  config/param_types.go
  daemon/daemon_test.go
  dataplane/linux/int_dataplane_test.go
  fv/health_test.go
  fv/infrastructure/infra_k8s.go
  fv/run-batches
  glide.lock
  glide.yaml
  go.mod
  go.sum
  k8sfv/calc_graph.go
  k8sfv/deployment.go
  k8sfv/namespace.go
  k8sfv/pod.go
  k8sfv/run-test
  proto/felixbackend.pb.go
Labels: docs-not-required, release-note-not-required

#2106 Fix Typo in int_dataplane.go
  dataplane/linux/int_dataplane.go
Labels: docs-pr-required, release-note-required

#2107 Have node pass buildinfo values as arguments rather than compiled in through LDFLAGS
  cmd/calico-felix/calico-felix.go
  daemon/daemon.go
  go.sum
Labels: docs-not-required, release-note-not-required

#2108 Remove incorrect go.sum entry for confd
  go.sum
Labels: docs-not-required, release-note-not-required

#2109 Re-instate felixbackend.pb.go
  proto/felixbackend.pb.go
Labels: docs-not-required, release-note-not-required

#2113 Cherry pick Drop IPIP packets originating in pods into release-v3.3
  dataplane/linux/endpoint_mgr_test.go
  rules/endpoints.go
  rules/endpoints_test.go
Labels: docs-pr-required, release-note-required

#2114 Cherry-pick Drop IPIP packets originating in pods into release-v3.2
  dataplane/linux/endpoint_mgr_test.go
  rules/endpoints.go
  rules/endpoints_test.go
Labels: docs-pr-required, release-note-required

#2115 Cherry-pick Drop IPIP packets originating in pods into release-v3.1
  dataplane/linux/endpoint_mgr_test.go
  rules/endpoints.go
  rules/endpoints_test.go
Labels: docs-pr-required, release-note-required

#2116 Cherry-pick Drop IPIP packets originating in pods into release-v3.0
  dataplane/linux/endpoint_mgr_test.go
  rules/endpoints.go
  rules/endpoints_test.go
Labels: docs-pr-required, release-note-required

#2111 Update OSS semaphore jobs that depend on glide
  Makefile
Labels: docs-not-required, release-note-not-required

#2112 fix misspelled words in logging message
  routetable/route_table.go
Labels: docs-not-required, release-note-not-required

#2085 Override etcd suboptions independent of the datastore type
  config/config_params.go
  config/config_params_test.go
  config/testdata/etcdcacertfile.cert
  config/testdata/etcdcacertfileother.cert
  config/testdata/etcdcertfile.cert
  config/testdata/etcdcertfileother.cert
  config/testdata/etcdkeyfile.key
  config/testdata/etcdkeyfileother.key
  testutils/file.go
Labels: docs-not-required, release-note-required

#2119 Change libcalico-go volume mount to be /go/src/github.com/projectcali…
  Makefile
Labels: docs-not-required, release-note-not-required

#2118 Only remove interface routes that were previously added by Felix
  config/config_params.go
  dataplane/driver.go
  dataplane/linux/int_dataplane.go
  go.mod
  go.sum
  routetable/route_table.go
  routetable/route_table_test.go
Labels: docs-pr-required, release-note-required

#2122 Pass in user.name and user.email instead of --author in git-commit, and define GOPATH for go modules cachine when it is not specified by the environment
  Makefile
Labels: docs-not-required, release-note-not-required

#2101 Properly manage route with VXLANMode CrossSubnet
  calc/calc_graph.go
  calc/vxlan_resolver.go
  config/config_params.go
  config/config_params_test.go
  daemon/daemon.go
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/endpoint_mgr_test.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/ipip_mgr_test.go
  dataplane/linux/vxlan_mgr.go
  dataplane/linux/vxlan_mgr_test.go
  fv/containers/containers.go
  fv/infrastructure/infra_etcd.go
  fv/infrastructure/infra_k8s.go
  fv/infrastructure/topology.go
  fv/vxlan_test.go
  proto/felixbackend.pb.go
  proto/felixbackend.proto
  routetable/route_table.go
Labels: docs-pr-required, release-note-required

#2126 Update typha's pin and run 'go list' in a docker
  Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2127 Handle VXLAN mode changes
  calc/vxlan_resolver.go
Labels: docs-not-required, release-note-not-required

#2128 Use node resource updates with Typha
  calc/calc_graph.go
  calc/vxlan_resolver.go
  config/config_params.go
  config/config_params_test.go
  daemon/daemon.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required
