Repository projectcalico/felix, pull requests merged in 2019-05, with the labels that each got.

#2018 Always rebuild when DEV_BUILD=true
  Makefile
Labels: docs-not-required, release-note-not-required

#2020 Use debian base for Felix
  docker-image/Dockerfile.amd64
  docker-image/calico-felix-wrapper
  fv/latency_test.go
  fv/workload/workload.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#2022 Increase K8s version to 1.14.1
  Makefile
Labels: docs-not-required, release-note-not-required

#2017 Form Typha address string correctly with an IPv6 address
  config/param_types.go
  daemon/daemon.go
  daemon/daemon_suite_test.go
  daemon/daemon_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#2023 Fix slow leak in endpoint_mgr
  dataplane/linux/endpoint_mgr.go
Labels: docs-not-required, release-note-required

#2024 v3.7 Cherry-pick: Fix slow leak in endpoint_mgr
  dataplane/linux/endpoint_mgr.go
Labels: docs-not-required, hold-merge, release-note-required

#2026 v3.5 Cherry-pick: Fix slow leak in endpoint_mgr
  dataplane/linux/endpoint_mgr.go
Labels: docs-not-required, release-note-required

#2025 v3.6 Cherry-pick: Fix slow leak in endpoint_mgr
  dataplane/linux/endpoint_mgr.go
Labels: docs-not-required, hold-merge, release-note-required
