Repository projectcalico/felix, pull requests merged in 2019-06, with the labels that each got.

#2030 Fix that routes were not re-sent if node IPs changed.
  calc/calc_graph_fv_test.go
  calc/resources_for_test.go
  calc/states_for_test.go
  calc/vxlan_resolver.go
  dataplane/mock/mock_dataplane.go
Labels: docs-pr-required, release-note-required

#2029 Added code and test to enable vxlan MAC if present in node spec.
  calc/calc_graph_fv_test.go
  calc/resources_for_test.go
  calc/states_for_test.go
  calc/vxlan_resolver.go
  config/config_params.go
  config/config_params_test.go
Labels: docs-pr-required, release-note-required

#2031 dataplane: accelerate sockets between app and the envoy sidecar through sockmap
  .gitignore
  Makefile
  bpf/bpf.go
  bpf/include/bpf.h
  bpf/mock_bpf_lib.go
  bpf/packrd/packed-packr.go
  bpf/sockmap/redir.c
  bpf/sockmap/sockops.c
  bpf/sockmap/sockops.h
  bpf/xdp/filter.c
  config/config_params.go
  dataplane/driver.go
  dataplane/linux/callbacks.go
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/sockmap_state.go
  fv/sockops_test.go
  glide.lock
  glide.yaml
Labels: docs-pr-required, release-note-required

#2034 Automated cherry pick of #2030: Improve calc graph test infra: - avoid adding empty state
  calc/calc_graph_fv_test.go
  calc/resources_for_test.go
  calc/states_for_test.go
  calc/vxlan_resolver.go
  dataplane/mock/mock_dataplane.go
Labels: docs-not-required, release-note-required

#2033 bpf: fix byte order
  bpf/bpf.go
  bpf/bpf_test.go
  bpf/include/bpf.h
  bpf/packrd/packed-packr.go
  bpf/sockmap/redir.c
  bpf/sockmap/sockops.c
Labels: docs-pr-required, release-note-required

#2028 Add support for NATOutgoingAddress option
  config/config_params.go
  dataplane/driver.go
  glide.lock
  glide.yaml
  rules/nat.go
  rules/nat_test.go
  rules/rule_defs.go
Labels: docs-pr-required, release-note-required

#2038 [release-v3.7] Automatic patch of libcalico-go to 8898b03e9d624b38f903a530ffc40f8a39a433d9
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#2039 Rename SockmapEnabled to SidecarAccelerationEnabled.
  config/config_params.go
  dataplane/driver.go
  dataplane/linux/int_dataplane.go
  fv/sockops_test.go
  glide.lock
  glide.yaml
Labels: docs-completed, release-note-not-required

#2040 Rename SockmapEnabled to SidecarAccelerationEnabled.
  config/config_params.go
  dataplane/driver.go
  dataplane/linux/int_dataplane.go
  fv/sockops_test.go
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#2041 [v3.8] Merge pull request #2036 from kinvolk/kinvolk/sockmap-fv
  .gitignore
  Makefile
  bpf/bpf.go
  config/config_params.go
  dataplane/driver.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/sockmap_state.go
  fv/sockmap_test.go
  fv/sockops_test.go
  fv/test-connection/test-connection.go
  fv/test-workload/test-workload.go
  fv/utils/utils.go
  fv/workload/workload.go
Labels: docs-not-required, release-note-not-required

#2044 Add explicit license to BPF program.
  Makefile
  bpf/bpf_test.go
  bpf/packrd/packed-packr.go
  bpf/xdp/filter.c
Labels: docs-pr-required, release-note-required

#2043 Include explicit license in BPF programs.
  Makefile
  bpf/bpf_test.go
  bpf/packrd/packed-packr.go
  bpf/sockmap/redir.c
  bpf/sockmap/sockops.c
  bpf/xdp/filter.c
Labels: docs-pr-required, release-note-required

#2042 Include explicit license in BPF programs.
  Makefile
  bpf/bpf_test.go
  bpf/packrd/packed-packr.go
  bpf/sockmap/redir.c
  bpf/sockmap/sockops.c
  bpf/xdp/filter.c
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#2045 Workaround goimports removing packr-generated import
  Makefile
  bpf/packrd/packed-packr.go
Labels: docs-pr-required, release-note-required

#2047 bpf: require kernel v4.20 for sockmap acceleration
  bpf/bpf.go
Labels: docs-not-required, release-note-not-required

#2046 bpf: require kernel v4.20 for sockmap acceleration
  bpf/bpf.go
Labels: docs-pr-required, release-note-not-required

#2055 Cherry pick 6fd3f67660c58b14553021e7f2f20042d32fb56e into v3.8
  Makefile
  bpf/packrd/packed-packr.go
Labels: docs-not-required, release-note-not-required

#2054 Cherry pick 6fd3f67660c58b14553021e7f2f20042d32fb56e into v3.7
  Makefile
  bpf/packrd/packed-packr.go
Labels: docs-not-required, release-note-not-required

#2056 Remove disputed contributions
  bpf/include/bpf.h
  bpf/sockmap/sockops.c
  bpf/xdp/filter.c
Labels: docs-pr-required, release-note-required

#2057 Remove disputed contributions
  bpf/include/bpf.h
  bpf/sockmap/sockops.c
  bpf/xdp/filter.c
Labels: docs-pr-required, release-note-required

#2058 Remove disputed contributions
  bpf/xdp/bpf.h
  bpf/xdp/filter.c
Labels: docs-pr-required, release-note-required

#2059 Fix build and tests
  Makefile
  bpf/bpf-packr.go
  bpf/bpf.go
  bpf/bpf_test.go
  bpf/packrd/packed-packr.go
  config/config_params.go
Labels: docs-not-required, release-note-not-required

#2060 Automated cherry pick of #2059: Fix build and tests
  Makefile
  bpf/bpf-packr.go
  bpf/bpf.go
  bpf/bpf_test.go
  bpf/packrd/packed-packr.go
  config/config_params.go
Labels: docs-not-required, release-note-not-required

#2061 Automated cherry pick of #2059: Fix build and tests
  Makefile
  bpf/bpf-packr.go
  bpf/bpf.go
  bpf/bpf_test.go
  bpf/packrd/packed-packr.go
  config/config_params.go
Labels: docs-not-required, release-note-not-required

#2067 Disallow enabling of XDP features
  dataplane/driver.go
  fv/ipip_test.go
  fv/latency_test.go
  fv/workload/workload.go
  git-hooks/files-to-skip
Labels: docs-pr-required, release-note-required

#2069 Disallow enabling XDP
  dataplane/driver.go
Labels: docs-completed, release-note-not-required

#2052 Drop VXLAN and IPIP packets originating in pods
  dataplane/linux/endpoint_mgr_test.go
  fv/ipip_test.go
  fv/vxlan_test.go
  rules/endpoints.go
  rules/endpoints_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#2068 FV flakes: fix for one and investigation for another
  fv/ipip_test.go
  fv/latency_test.go
  fv/workload/workload.go
Labels: docs-not-required, release-note-not-required

#2062 Drop VXLAN and IPIP packets originating in pods (v3.8)
  dataplane/linux/endpoint_mgr_test.go
  fv/ipip_test.go
  fv/vxlan_test.go
  rules/endpoints.go
  rules/endpoints_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#2063 Drop VXLAN and IPIP packets originating in pods (v3.7)
  dataplane/linux/endpoint_mgr_test.go
  fv/ipip_test.go
  fv/vxlan_test.go
  rules/endpoints.go
  rules/endpoints_test.go
Labels: docs-not-required, release-note-not-required

#2064 Drop IPIP packets originating in pods (v3.6)
  dataplane/linux/endpoint_mgr_test.go
  fv/ipip_test.go
  rules/endpoints.go
  rules/endpoints_test.go
Labels: docs-not-required, release-note-not-required

#2065 Drop IPIP packets originating in pods (v3.5)
  dataplane/linux/endpoint_mgr_test.go
  fv/ipip_test.go
  rules/endpoints.go
  rules/endpoints_test.go
Labels: docs-not-required, release-note-not-required
