Repository projectcalico/felix, pull requests merged in 2020-02, with the labels that each got.

#2216 Pin packr to v2.5.2.
  bpf/packrd/packed-packr.go
  docker-build-images/bpf-clang-builder.Dockerfile.amd64
Labels: cherry-pick-candidate, docs-pr-required, release-note-required

#2215 Report liveness from various loops.
  calc/async_calc_graph.go
  dataplane/linux/int_dataplane.go
  iptables/table.go
Labels: docs-pr-required, release-note-required

#2217 Automated cherry pick of #2216: Pin packr to v2.5.2.
  bpf/packrd/packed-packr.go
  docker-build-images/bpf-clang-builder.Dockerfile.amd64
Labels: docs-not-required, release-note-not-required

#2218 Automated cherry pick of #2216: Pin packr to v2.5.2.
  bpf/packrd/packed-packr.go
  docker-build-images/bpf-clang-builder.Dockerfile.amd64
Labels: docs-not-required, release-note-not-required

#2158 Experimental Semaphore v2 manifest.
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#2221 Fix IP used in ICMP responses to workloads.
  dataplane/linux/bpf_ep_mgr.go
Labels: docs-pr-required, release-note-required
