Repository projectcalico/felix, pull requests merged in 2020-10, with the labels that each got.

#2515 Semaphore Auto Pin Update PR
  config/config_params_test.go
  config/env_var_loader_test.go
  config/file_loader_test.go
  config/param_types_test.go
  dataplane/linux/intdataplane_fv_suite_test.go
  go.mod
  go.sum
  iptables/iptables_fv_suite_test.go
  k8sfv/k8sfv.go
Labels: docs-not-required, release-note-not-required

#2516 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2507 Adding ec2 health fix and fv health status test
  dataplane/driver.go
  fv/aws_test.go
Labels: docs-pr-required, release-note-required

#2499 Address/Investigate a WG fv flake
  fv/wireguard_test.go
Labels: docs-not-required, release-note-not-required

#2517 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2521 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2523 bpf: enforce RPF check for possible spoofed TCP
  bpf-gpl/conntrack.h
Labels: docs-pr-required, release-note-required

#2497 bpf/proxy: add info logging when Syncer iteration start/ends
  bpf/proxy/syncer.go
Labels: docs-pr-required, release-note-required

#2525 Update go-build version to v0.48 (go 1.15.2)
  Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2528 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2508 Multiple node addresses result in multiple routes
  calc/calc_graph_fv_test.go
  calc/l3_route_resolver.go
  calc/states_for_test.go
  dataplane/linux/bpf_route_mgr.go
  fv/bpf_test.go
  fv/infrastructure/felix.go
  fv/infrastructure/infra_k8s.go
  fv/infrastructure/topology.go
Labels: docs-pr-required, release-note-required

#2530 Moving the CGO functions to a separate C file
  bpf/bpf_syscall.go
  bpf/bpf_syscall.h
Labels: docs-pr-required, release-note-required

#2529 Fix L2 dataplane reconciliation
  routetable/route_table.go
Labels: docs-not-required, release-note-not-required

#2531 bpf: skip FIB for WEP egress leaving the cluster
  bpf-gpl/conntrack.h
  bpf-gpl/jump.h
  bpf-gpl/tc.c
  fv/bpf_test.go
  fv/infrastructure/topology.go
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#2533 bpf: skip FIB for WEP egress leaving the cluster - backport 3.16
  bpf-gpl/conntrack.h
  bpf-gpl/jump.h
  bpf-gpl/tc.c
  fv/bpf_test.go
  fv/infrastructure/topology.go
Labels: docs-not-required, release-note-required

#2532 Service loop prevention
  calc/calc_graph.go
  calc/calc_graph_test.go
  calc/dataplane_passthru.go
  calc/event_sequencer.go
  calc/profile_decoder_test.go
  config/config_params.go
  dataplane/driver.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/intdataplane_ut_suite_test.go
  dataplane/linux/service_loop_mgr.go
  fv/service_loop_prevention_test.go
  go.mod
  go.sum
  iptables/actions.go
  proto/felixbackend.pb.go
  proto/felixbackend.proto
  rules/nat.go
  rules/rule_defs.go
  rules/static.go
  rules/static_test.go
Labels: docs-pr-required, release-note-required

#2541 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2542 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2535 Fix wireguard resync processing: correctly flag already handled nodes
  netlinkshim/mocknetlink/netlink.go
  netlinkshim/mocknetlink/wireguard.go
  wireguard/wireguard.go
  wireguard/wireguard_test.go
Labels: docs-not-required, release-note-required

#2546 Export multipath route to kernel
  etc/bird/calico-bird.conf.template
Labels: docs-not-required, merge-when-ready, release-note-not-required

#2511 Calculate MTU based on host interfaces
  config/config_params.go
  dataplane/driver.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/int_dataplane_test.go
  dataplane/linux/vxlan_mgr.go
  fv/bpf_test.go
  fv/test-workload/test-workload.go
  fv/vxlan_test.go
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2538 bpf: pick a random backend after affinity timeo expires
  bpf-gpl/nat.h
  bpf/maps.go
  bpf/proxy/syncer.go
  fv/bpf_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-required
