Repository projectcalico/felix, pull requests merged in 2020-12, with the labels that each got.

#2611 Use -target bpf in bpf-apache builds
  bpf-apache/Makefile
  bpf-apache/bpf.h
  bpf-apache/filter.c
  bpf/bpf_test.go
Labels: docs-not-required, release-note-not-required

#2614 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2613 Use Typha's discovery library
  config/config_params.go
  daemon/daemon.go
Labels: docs-not-required, release-note-required

#2617 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2610 Refactor BPF ipsets code as an "ipsetsDataplane"
  bpf/ipsets/ipsets.go
  bpf/ipsets/map.go
  bpf/maps.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/ipip_mgr.go
  dataplane/linux/mock_ipsets_for_test.go
Labels: docs-not-required, release-note-not-required

#2621 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2623 [v3.16] Backport Typha discovery
  config/config_params.go
  daemon/daemon.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2620 bpf: encap nodeport return from host networked pods
  bpf-gpl/tc.c
  bpf/ut/nat_test.go
Labels: cherry-pick-candidate, docs-pr-required, release-note-required

#2624 [v3.17] bpf: encap nodeport return from host networked pods
  bpf-gpl/tc.c
  bpf/ut/nat_test.go
Labels: docs-pr-required, release-note-required

#2627 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2626 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2628 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2629 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2630 bpf: fixup dst MAC for host networked nodeport backends
  bpf-gpl/tc.c
  bpf/ut/nat_test.go
Labels: docs-pr-required, release-note-required

#2631 [v3.17] Backport BPF fixes for node ports
  bpf-gpl/arp.h
  bpf-gpl/bpf.h
  bpf-gpl/calculate-flags
  bpf-gpl/conntrack.h
  bpf-gpl/skb.h
  bpf-gpl/tc.c
  bpf/arp/map.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/nat_test.go
  cmd/calico-bpf/commands/arp.go
  dataplane/linux/int_dataplane.go
  fv/bpf_test.go
Labels: docs-not-required, release-note-required

#2633 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2634 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2632 BPF conntrack scanner moved outside of kube-proxy
  bpf/conntrack/cleanup.go
  bpf/conntrack/conntrack_test.go
  bpf/conntrack/scanner.go
  bpf/proxy/health_check_nodeport_test.go
  bpf/proxy/kube-proxy.go
  bpf/proxy/options.go
  bpf/proxy/proxy.go
  bpf/proxy/proxy_bench_test.go
  bpf/proxy/proxy_test.go
  bpf/proxy/syncer.go
  bpf/proxy/syncer_test.go
  dataplane/linux/int_dataplane.go
  fv/bpf_test.go
Labels: docs-pr-required, release-note-required

#2609 BPF policy code reshuffle for easier maintainability
  bpf/polprog/pol_prog_builder.go
  bpf/polprog/pol_prog_builder_test.go
  bpf/state/map.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/icmp_related_test.go
  bpf/ut/pol_prog_test.go
  dataplane/linux/bpf_ep_mgr.go
Labels: docs-pr-required, release-note-required

#2636 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2635 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2637 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2638 Run BPF logger as part of FV infrastructure whenever BPF is enabled
  fv/bpf_test.go
  fv/config_update_test.go
  fv/etcd_restart_test.go
  fv/infrastructure/infra_etcd.go
  fv/infrastructure/infra_k8s.go
  fv/infrastructure/topology.go
  fv/ingress_egress_test.go
  fv/latency_test.go
  fv/named_ports_test.go
  fv/netsets_test.go
  fv/policysync_test.go
  fv/rule_metadata_test.go
Labels: docs-not-required, release-note-not-required

#2640 Exit with success at end of collect-artifacts script
  .semaphore/collect-artifacts
Labels: docs-not-required, release-note-not-required

#2641 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2642 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2644 Exit with success at end of collect-artifacts script
  .semaphore/collect-artifacts
Labels: docs-not-required, release-note-not-required

#2648 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
