Repository projectcalico/felix, pull requests merged in 2020-01, with the labels that each got.

#2198 Upgrade reuse lib and don't fork sctp lib
  fv/test-connection/test-connection.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2200 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2204 Update pins
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2203 release-v3.8 - Update pins
  check-licenses/check_licenses.go
  glide.lock
  glide.yaml
Labels: docs-not-required, release-note-not-required

#2202 release-v3.10 - Update pins
  bpf/packrd/packed-packr.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2201 release-v3.9 - Update pins
  bpf/packrd/packed-packr.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2205 release-v3.8 - Fix dirty builds
  Makefile
Labels: docs-not-required, release-note-not-required

#2206 release-v3.9 - Fix dirty builds
  Makefile
Labels: docs-not-required, release-note-not-required

#2208 release-v3.10 - Fix dirty builds
  Makefile
Labels: docs-not-required, release-note-not-required

#2207 Lazily set LDFLAGS so we get a more accurate GitVersion for the build
  Makefile
Labels: docs-not-required, release-note-not-required

#2189 Use iptables for ipv4 RPF check
  config/config_params.go
  config/config_params_test.go
  dataplane/driver.go
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/endpoint_mgr_test.go
  dataplane/linux/int_dataplane.go
  fv/spoof_test.go
  fv/test-connection/test-connection.go
  fv/workload/workload.go
  rules/static.go
  rules/static_test.go
Labels: docs-pr-required, release-note-required

#2209 rule metadata
  calc/rule_convert.go
  calc/rule_convert_test.go
  calc/rule_scanner.go
  calc/rule_scanner_test.go
  dataplane/linux/endpoint_mgr_test.go
  dataplane/linux/xdp_state.go
  dataplane/linux/xdp_state_test.go
  go.mod
  go.sum
  iptables/rules.go
  iptables/rules_test.go
  iptables/table_test.go
  proto/felixbackend.pb.go
  proto/felixbackend.proto
  rules/dispatch.go
  rules/dispatch_test.go
  rules/endpoints.go
  rules/endpoints_test.go
  rules/policy.go
  rules/policy_test.go
  rules/static.go
  rules/static_test.go
Labels: docs-completed, release-note-required

#2210 Cleanup unused IgnoreLooseRPF field
  config/config_params_test.go
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2211 FV tests for rule metadata
  fv/rule_metadata_test.go
Labels: docs-completed, release-note-not-required
