Repository projectcalico/felix, pull requests merged in 2020-06, with the labels that each got.

#2350 update k8s libraries to v1.17.2
  bpf/proxy/proxy.go
  bpf/proxy/proxy_test.go
  bpf/proxy/syncer.go
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2366 update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2353 Adding support for Load balancer SourceIPRange
  bpf-gpl/connect_balancer.c
  bpf-gpl/nat.h
  bpf-gpl/reasons.h
  bpf-gpl/tc.c
  bpf/nat/maps.go
  bpf/proxy/lb_src_range_test.go
  bpf/proxy/syncer.go
  fv/bpf_test.go
Labels: docs-pr-required, release-note-required

#2369 Addressing workload traffic flake.
  fv/wireguard_test.go
Labels: docs-not-required, release-note-not-required

#2364 BPF: small fixes
  bpf-gpl/connect_balancer.c
  cmd/calico-bpf/commands/nat.go
  fv/bpf_test.go
Labels: docs-pr-required, release-note-required

#2365 Fix up README badges
  README.md
Labels: docs-not-required, release-note-not-required

#2372 Update wireguard tests: use functions for Eventually, stop checking Felix PIDs
  fv/wireguard_test.go
Labels: docs-pr-required, release-note-required

#2379 Use 20.04 for the wgtool image.
  fv/Dockerfile.wgtool.amd64
Labels: docs-not-required, release-note-not-required

#2376 Update pins / fix prometheus client
  calc/async_calc_graph.go
  dataplane/linux/int_dataplane.go
  go.mod
  go.sum
  ipsets/ipset_defs.go
  iptables/lock.go
  routetable/route_table.go
Labels: docs-not-required, release-note-required

#2378 Include wireguard tunnel IP address in wireguard routing
  calc/l3_route_resolver.go
  dataplane/driver.go
  dataplane/linux/bpf_route_mgr.go
  dataplane/linux/wireguard_mgr.go
  fv/infrastructure/felix.go
  fv/infrastructure/infra_etcd.go
  fv/infrastructure/infra_k8s.go
  fv/infrastructure/infrastructure.go
  fv/infrastructure/topology.go
  fv/tcpdump/tcpdump.go
  fv/wireguard_test.go
  proto/felixbackend.pb.go
  proto/felixbackend.proto
  rules/rule_defs.go
  rules/static.go
  wireguard/wireguard.go
  wireguard/wireguard_test.go
Labels: docs-not-required, release-note-not-required

#2382 Add typha port to failsafes
  config/config_params.go
  config/config_params_test.go
  fv/hostendpoints_test.go
  fv/test-connection/test-connection.go
  proto/felixbackend.pb.go
Labels: docs-pr-required, release-note-required

#2383 Update pins
  config/config_params.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2362 Adding more WireGuard FVs
  fv/wireguard_test.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2384 Fix flake in config FV test.
  fv/config_update_test.go
Labels: docs-not-required, release-note-not-required

#2385 Free up space on the build machine as recommended by Semaphore support.
  .semaphore/semaphore.yml
Labels: area/build, docs-not-required, release-note-not-required

#2374 bpf: Map.Iter() uses bpf.GetMapNextKey syscall
  bpf/bpf_syscall.go
  bpf/bpf_syscall_stub.go
  bpf/conntrack/cleanup.go
  bpf/maps.go
  bpf/mock/map.go
  bpf/nat/maps.go
  bpf/proxy/syncer_test.go
  bpf/ut/bpf_prog_test.go
  cmd/calico-bpf/commands/conntrack.go
  cmd/calico-bpf/commands/ipsets.go
  cmd/calico-bpf/commands/nat.go
  cmd/calico-bpf/commands/routes.go
  dataplane/linux/bpf_route_mgr.go
Labels: docs-pr-required, release-note-required

#2387 BPF fv ipip host networked test
  fv/bpf_test.go
  fv/infrastructure/topology.go
Labels: docs-pr-required, release-note-required

#2390 Update libcalico-go pin
  config/config_params.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2391 [PICK MULTIPLE] Fix flaky tests
  .semaphore/semaphore.yml
  Makefile
  fv/Dockerfile.test.amd64
  fv/config_update_test.go
  fv/fv_infra_test.go
Labels: docs-not-required, release-note-not-required

#2392 Fix up formatting and make sure protobuf file gets formatted.
  Makefile
  fv/wireguard_test.go
  proto/felixbackend.pb.go
  rules/rule_defs.go
Labels: docs-pr-required, release-note-required

#2373 BPF Proxy cleans up conntrack
  bpf/conntrack/cleanup.go
  bpf/conntrack/conntrack_test.go
  bpf/conntrack/map.go
  bpf/nat/maps.go
  bpf/proxy/health_check_nodeport_test.go
  bpf/proxy/kube-proxy.go
  bpf/proxy/kube-proxy_test.go
  bpf/proxy/lb_src_range_test.go
  bpf/proxy/options.go
  bpf/proxy/proxy.go
  bpf/proxy/proxy_test.go
  bpf/proxy/syncer.go
  bpf/proxy/syncer_test.go
  dataplane/linux/bpf_conntrack_mgr.go
  dataplane/linux/int_dataplane.go
Labels: docs-pr-required, release-note-required

#2380 Reject connections to services with no backends
  bpf-gpl/connect_balancer.c
  bpf-gpl/icmp.h
  bpf-gpl/jump.h
  bpf-gpl/nat.h
  bpf-gpl/tc.c
  bpf-gpl/ut/icmp_port_unreachable.c
  bpf/ut/bpf_prog_test.go
  bpf/ut/icmp_port_unreachable_test.go
  fv/bpf_test.go
  fv/connectivity/conncheck.go
  fv/test-connection/test-connection.go
Labels: docs-not-required, release-note-required

#2363 Make TC program application graceful
  bpf/tc/attach.go
  bpf/ut/attach_test.go
  bpf/ut/precompilation_test.go
  dataplane/linux/bpf_ep_mgr.go
  fv/bpf_test.go
  go.sum
Labels: docs-not-required, release-note-required

#2397 Remove FORCE_WIREGUARD_FV
  .semaphore/cleanup.yml
  .semaphore/semaphore.yml
  Makefile
Labels: docs-not-required, release-note-not-required

#2399 Remove compiler logic that is now unused
  bpf/tc/compiler.go
Labels: docs-not-required, release-note-not-required

#2389 Add BPF dataplane support for Wireguard
  bpf-gpl/bpf.h
  bpf-gpl/calculate-flags
  bpf-gpl/list-objs
  bpf-gpl/skb.h
  bpf-gpl/tc.c
  bpf/tc/attach.go
  bpf/tc/compiler.go
  config/config_params.go
  dataplane/linux/bpf_ep_mgr.go
Labels: docs-pr-required, release-note-required

#2402 FV: Print container log lines without additional log header
  fv/containers/containers.go
Labels: docs-not-required, release-note-not-required

#2395 bpf/proxy flaky UTs fixes
  bpf/proxy/proxy.go
  bpf/proxy/proxy_test.go
Labels: docs-pr-required, release-note-required

#2394 bpf: Reduced allocations in map related syscalls
  bpf/bpf_syscall.go
  bpf/ut/bpf_prog_test.go
Labels: docs-pr-required, release-note-required

#2393 fv: ExpectConnectivity is a universal expectation
  fv/bpf_test.go
  fv/connectivity/conncheck.go
Labels: docs-pr-required, release-note-required

#2401 BPF proxy startup fix
  bpf/proxy/lb_src_range_test.go
  bpf/proxy/syncer.go
  bpf/proxy/syncer_bench_test.go
Labels: docs-not-required, release-note-required

#2405 fv: dumpNATmaps executes in parallel
  fv/bpf_test.go
Labels: docs-pr-required, release-note-required

#2398 New unit and FV tests to test service type changes
  bpf/proxy/service_type_change_test.go
  fv/bpf_test.go
Labels: docs-pr-required, release-note-required
