Repository projectcalico/felix, pull requests merged in 2020-08, with the labels that each got.

#2430 Update Dockerfile.s390x
  docker-image/Dockerfile.s390x
Labels: docs-pr-required, release-note-required

#2439 Remove vendor dir if it exists on clean
  Makefile
Labels: docs-not-required, release-note-not-required

#2440 Bpf/proxy: less evaluations/allocs for debug prints
  bpf/mock/map.go
  bpf/proxy/kube-proxy_test.go
  bpf/proxy/proxy_bench_test.go
  bpf/proxy/service_type_change_test.go
  bpf/proxy/syncer.go
  bpf/proxy/syncer_bench_test.go
  bpf/proxy/syncer_test.go
Labels: docs-not-required, release-note-not-required

#2445 Fix race between interface deletion and cleanup.
  bpf/bpf_syscall.go
  bpf/tc/attach.go
  bpf/ut/attach_test.go
  bpf/ut/precompilation_test.go
  dataplane/linux/bpf_ep_mgr.go
Labels: docs-not-required, release-note-not-required

#2441 Optimise map iteration
  bpf/bpf_defs.go
  bpf/bpf_syscall.go
  bpf/bpf_syscall_stub.go
  bpf/conntrack/cleanup.go
  bpf/conntrack/conntrack_suite_test.go
  bpf/conntrack/conntrack_test.go
  bpf/conntrack/map.go
  bpf/maps.go
  bpf/mock/map.go
  bpf/nat/maps.go
  bpf/proxy/syncer.go
  bpf/proxy/syncer_test.go
  bpf/routes/map.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/maps_test.go
  bpf/ut/pol_prog_test.go
  cmd/calico-bpf/commands/conntrack.go
  cmd/calico-bpf/commands/ipsets.go
  cmd/calico-bpf/commands/routes.go
  dataplane/linux/bpf_ip_set_mgr.go
  dataplane/linux/bpf_route_mgr.go
  fv/bpf_test.go
  timeshim/mocktime/mocktime.go
  timeshim/time.go
Labels: docs-not-required, release-note-not-required

#2443 Reintroduce windows support
  Makefile
  daemon/daemon.go
  dataplane/driver.go
  dataplane/driver_windows.go
  dataplane/windows/endpoint_mgr.go
  dataplane/windows/hcn/hcn_linux.go
  dataplane/windows/hcn/hcn_windows.go
  dataplane/windows/hns/hns_linux.go
  dataplane/windows/hns/hns_windows.go
  dataplane/windows/ipsets/ipset_defs.go
  dataplane/windows/ipsets/ipsets.go
  dataplane/windows/ipsets_mgr.go
  dataplane/windows/ipsets_mgr_test.go
  dataplane/windows/policy_mgr.go
  dataplane/windows/policy_mgr_test.go
  dataplane/windows/policysets/policyset_defs.go
  dataplane/windows/policysets/policysets.go
  dataplane/windows/policysets/policysets_test.go
  dataplane/windows/vxlan_mgr.go
  dataplane/windows/vxlan_mgr_test.go
  dataplane/windows/win_dataplane.go
  dataplane/windows/win_dataplane_test.go
  dataplane/windows/windataplane_ut_suite_test.go
  go.mod
  go.sum
  iputils/intersect.go
  iputils/intersect_test.go
  jitter/jittered_ticker.go
  jitter/jittered_ticker_test.go
  logutils/logutils_windows.go
Labels: docs-pr-required, release-note-required

#2447 Reduce log spam from missing interfaces.
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/endpoint_mgr_test.go
Labels: docs-not-required, release-note-required

#2448 Fix slow retries in route_table and finesse logging.
  routetable/route_table.go
Labels: docs-not-required, release-note-required

#2449 Fix that profile refs weren't cleaned up when removing endpoint.
  dataplane/linux/bpf_ep_mgr.go
Labels: docs-not-required, release-note-not-required

#2450 Reduce log spam
  bpf/bpf_syscall.go
  bpf/tc/attach.go
  calc/active_rules_calculator.go
  conntrack/conntrack.go
  conntrack/conntrack_test.go
  dataplane/linux/bpf_ep_mgr.go
  dataplane/linux/vxlan_mgr.go
  routetable/route_table.go
Labels: docs-not-required, release-note-not-required

#2451 Fix watchdog timeouts in various cases
  bpf/bpf_syscall.go
  bpf/tc/attach.go
  bpf/ut/bpf_prog_test.go
  calc/async_calc_graph.go
  dataplane/linux/bpf_ep_mgr.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/status_combiner.go
  go.mod
  go.sum
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#2452 bpf/ut: fix TestMapIterWithDelete*
  bpf/bpf_syscall.go
  bpf/bpf_syscall_stub.go
  bpf/ut/bpf_prog_test.go
Labels: docs-not-required, release-note-not-required

#2455 Fix leaks of BPF map and program FDs.
  bpf/bpf_defs.go
  bpf/ut/bpf_prog_test.go
  dataplane/linux/bpf_ep_mgr.go
Labels: docs-not-required, release-note-required

#2444 bpf/proxy: do not update unchanged services
  bpf/proxy/syncer.go
  bpf/proxy/syncer_bench_test.go
Labels: docs-not-required, release-note-not-required

#2453 bpf/conntrack: fix assumed ordering in NewStaleNATScanner
  bpf/conntrack/cleanup.go
  bpf/conntrack/conntrack_test.go
Labels: docs-not-required, release-note-not-required

#2454 bpf/proxy: Conntrack cleaner runs immediately after sync up
  bpf/proxy/kube-proxy.go
  bpf/proxy/proxy.go
Labels: docs-not-required, release-note-not-required

#2457 Always apply BPF programs to workload interfaces
  calc/async_calc_graph.go
  dataplane/linux/bpf_ep_mgr.go
Labels: docs-pr-required, release-note-required

#2456 BPF: allow host traffic when conntrack is full
  bpf-gpl/tc.c
  bpf/ut/bpf_prog_test.go
  bpf/ut/to_host_allowed_test.go
  bpf/ut/whitelist_test.go
  cmd/calico-bpf/commands/conntrack.go
  fv/bpf_test.go
Labels: docs-not-required, release-note-required

#2458 Fix incorrect handling of interface state in BPF mode.
  dataplane/linux/bpf_ep_mgr.go
Labels: docs-pr-required, release-note-required

#2459 Fix that we never cleaned up the BPF endpoint cache
  dataplane/linux/bpf_ep_mgr.go
  dataplane/linux/bpf_ip_set_mgr.go
Labels: docs-pr-required, release-note-required

#2460 [v3.16] Backport BPF fixes
  bpf-gpl/tc.c
  bpf/ut/bpf_prog_test.go
  bpf/ut/to_host_allowed_test.go
  bpf/ut/whitelist_test.go
  calc/async_calc_graph.go
  cmd/calico-bpf/commands/conntrack.go
  dataplane/linux/bpf_ep_mgr.go
  dataplane/linux/bpf_ip_set_mgr.go
  fv/bpf_test.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2461 BPF: If packet is too short, try to pull more data
  bpf-gpl/bpf.h
  bpf-gpl/skb.h
Labels: docs-not-required, release-note-required

#2462 [v3.16] BPF: If packet is too short, try to pull more data
  bpf-gpl/bpf.h
  bpf-gpl/skb.h
Labels: docs-not-required, release-note-required

#2471 BPF: Change data interface regex to avoid EKS workloads
  config/config_params.go
Labels: docs-pr-required, release-note-required

#2472 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2473 Add option for Felix.Stop to shutdown gracefully
  fv/infrastructure/felix.go
  fv/infrastructure/topology.go
Labels: docs-not-required, release-note-not-required

#2474 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2475 Log out k8s connection params, used in BPF mode.
  daemon/daemon.go
Labels: docs-not-required, release-note-required

#2477 Log out k8s connection params, used in BPF mode.
  daemon/daemon.go
Labels: docs-pr-required, release-note-required

#2476 Fix policy updates for Windows dataplane.
  dataplane/windows/endpoint_mgr.go
Labels: docs-not-required, release-note-not-required

#2478 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2479 Cherry-pick Merge pull request #2476 from song-jiang/song-policy-update
  dataplane/windows/endpoint_mgr.go
Labels: docs-not-required, release-note-not-required
