Repository projectcalico/felix, pull requests merged in 2020-11, with the labels that each got.

#2551 update netlink 1.0.0 -> 1.1.0
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2558 [master] Automatic update of sempahore YAMLs.
  .semaphore/cleanup.yml
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: docs-not-required, release-note-not-required

#2561 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2553 [v3.16] Backport src/desc/ check crash fix
  dataplane/driver.go
  fv/aws_test.go
Labels: docs-not-required, release-note-required

#2554 Fix service loop prevention in IPVS mode.
  rules/static.go
  rules/static_test.go
Labels: docs-not-required, release-note-not-required

#2562 Log in to dockerhub on remote VMs too.
  .semaphore/create-test-vm
Labels: docs-pr-required, release-note-required

#2564 Detect iptables-save error when run on a system with nft rules.
  iptables/table.go
  iptables/table_test.go
  iptables/utils_for_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#2555 Expand interface detection regexes.
  config/config_params.go
Labels: docs-not-required, release-note-required

#2565 Fix release branch pin update regex (add ^ to start) and cascade pin …
  .semaphore/semaphore.yml
  Makefile
Labels: docs-not-required, release-note-not-required

#2567 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-required

#2563 Handle when unable to detect host MTU
  dataplane/linux/int_dataplane.go
  fv/mtu_test.go
Labels: docs-not-required, release-note-not-required

#2569 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2570 Fix flaky MTU test wait time
  fv/vxlan_test.go
Labels: docs-not-required, release-note-not-required

#2571 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2573 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2576 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2549 bpf: nodeport return with multiple ifaces
  bpf-gpl/arp.h
  bpf-gpl/bpf.h
  bpf-gpl/calculate-flags
  bpf-gpl/conntrack.h
  bpf-gpl/skb.h
  bpf-gpl/tc.c
  bpf/arp/map.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/nat_test.go
  cmd/calico-bpf/commands/arp.go
  dataplane/linux/int_dataplane.go
  fv/bpf_test.go
Labels: docs-not-required, release-note-required

#2577 Turn down log level on spammy MTU log
  dataplane/linux/int_dataplane.go
Labels: docs-not-required, release-note-not-required

#2578 Automated cherry pick of #2577: Turn down log level on spammy MTU log
  dataplane/linux/int_dataplane.go
Labels: docs-not-required, release-note-not-required

#2580 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2583 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2485 bpf: use state from map, free up stack
  bpf-gpl/list-ut-objs
  bpf-gpl/tc.c
  bpf/ut/benchmarks_test.go
  bpf/ut/bpf_prog_test.go
Labels: docs-pr-required, release-note-required

#2585 Fix spammy log from conntrack cleanup.
  bpf/conntrack/cleanup.go
Labels: cherry-pick-candidate, docs-not-required, merge-when-ready, release-note-required

#2586 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2587 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2588 bpf/proxy: fix stale NAT entries cleanup
  bpf/proxy/syncer.go
Labels: docs-pr-required, release-note-required

#2589 [v3.16] bpf/proxy: fix stale NAT entries cleanup
  bpf/proxy/syncer.go
Labels: docs-not-required, release-note-required

#2590 [v3.17] bpf/proxy: fix stale NAT entries cleanup
  bpf/proxy/syncer.go
Labels: docs-not-required, release-note-required

#2591 Add TCP spoofing test, infra to monitor connections.
  fv/bpf_test.go
  fv/sockmap_test.go
  fv/test-connection/test-connection.go
  fv/workload/workload.go
Labels: docs-not-required, release-note-not-required

#2595 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2597 pin update
  bpf/proxy/service_type_change_test.go
  daemon/daemon.go
  fv/bpf_test.go
  fv/health_test.go
  fv/infrastructure/infra_k8s.go
  go.mod
  go.sum
  k8sfv/calc_graph.go
  k8sfv/deployment.go
  k8sfv/namespace.go
  k8sfv/pod.go
  k8sfv/pod_test.go
Labels: docs-not-required, release-note-not-required

#2592 Set aws-src-dst-check report ready
  dataplane/driver.go
Labels: docs-not-required, release-note-required

#2520 Enable UDP bypass, tighten RPF check accordingly
  bpf-gpl/conntrack.h
  bpf-gpl/tc.c
Labels: docs-not-required, release-note-required

#2598 [master] Semaphore Auto Pin Update
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2600 Automated cherry pick of #2592: Mark report status as ready
  dataplane/driver.go
Labels: docs-pr-required, release-note-required

#2603 Actually retry the BPF_PROG_TEST_RUN call.
  bpf/bpf_syscall.go
Labels: docs-pr-required, release-note-required

#2604 [v3.17] Backport source/dest readiness fix
  dataplane/driver.go
Labels: docs-not-required, release-note-required

#2601 NAT stale cleanup tests
  bpf/proxy/proxy.go
  fv/bpf_test.go
  fv/connectivity/conncheck.go
  fv/sockmap_test.go
  fv/workload/workload.go
Labels: docs-not-required, release-note-not-required

#2582 Fix application of normal HEP policy to traffic from host to a DNAT'd IP
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/endpoint_mgr_test.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/policy_mgr.go
  dataplane/linux/policy_mgr_test.go
  fv/hostendpoints_test.go
  fv/infrastructure/felix.go
  fv/ipip_test.go
  fv/vxlan_test.go
  iptables/match_builder.go
  iptables/table.go
  rules/dispatch.go
  rules/endpoints.go
  rules/endpoints_test.go
  rules/policy.go
  rules/rule_defs.go
  rules/static.go
  rules/static_test.go
Labels: docs-not-required, release-note-required

#2606 Fix placing of filter-FORWARD Accept bit for signaling to mangle-POSTROUTING chain
  fv/forward_drop_test.go
  rules/static.go
  rules/static_test.go
Labels: docs-not-required, release-note-not-required
