Repository projectcalico/felix, pull requests merged in 2020-05, with the labels that each got.

#2291 Delay felix startup
  docker-image/calico-felix-wrapper
Labels: docs-pr-required, release-note-required

#2288 [v3.14] Backport version check for BPF mode.
  bpf/bpf.go
  config/config_params.go
  config/config_params_test.go
  daemon/daemon.go
Labels: docs-not-required, release-note-required

#2290 BPF: NodePorts on multi-homed nodes
  bpf-gpl/tc.c
  bpf/ut/bpf_prog_test.go
  bpf/ut/nat_encap_test.go
  bpf/ut/nat_test.go
  fv/bpf_test.go
Labels: docs-pr-required, release-note-required

#2286 Create a wireguard rule for each local source CIDR
  calc/event_sequencer.go
  dataplane/linux/wireguard_mgr.go
  ip/ip_addr.go
  netlink/mock/netlink.go
  proto/felixbackend.pb.go
  proto/felixbackend.proto
  routerule/rule_lib.go
  routetable/route_table.go
  wireguard/wireguard.go
  wireguard/wireguard_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#2293 Cherry-pick wireguard commits into release-v3.14
  calc/event_sequencer.go
  dataplane/linux/wireguard_mgr.go
  docker-image/calico-felix-wrapper
  ip/ip_addr.go
  netlink/mock/netlink.go
  proto/felixbackend.pb.go
  proto/felixbackend.proto
  routerule/dataplane_shims.go
  routerule/route_rule.go
  routerule/route_rule_test.go
  routerule/routerule_suite_test.go
  routerule/rule_lib.go
  routerule/rule_lib_test.go
  routetable/route_table.go
  wireguard/wireguard.go
  wireguard/wireguard_test.go
Labels: docs-not-required, release-note-not-required

#2294 Ensure table index is assigned to wireguard even when disabled
  dataplane/driver.go
Labels: docs-pr-required, release-note-required

#2295 Ensure table index is assigned to wireguard even when disabled
  dataplane/driver.go
Labels: docs-pr-required, release-note-required

#2296 [v3.14] BPF: NodePorts on multi-homed nodes
  bpf-gpl/tc.c
  bpf/ut/bpf_prog_test.go
  bpf/ut/nat_encap_test.go
  bpf/ut/nat_test.go
  fv/bpf_test.go
Labels: docs-not-required, release-note-required

#2298 Deflake tests that dump BPF maps
  bpf/proxy/kube-proxy.go
  fv/bpf_test.go
  fv/containers/containers.go
  fv/fv_infra_test.go
Labels: docs-not-required, release-note-not-required

#2297 Add local throw routes to wireguard table
  wireguard/wireguard.go
  wireguard/wireguard_test.go
Labels: docs-pr-required, release-note-required

#2301 Fix conntrack deletion
  netlink/mock/netlink.go
  routetable/route_table.go
  routetable/route_table_test.go
Labels: docs-pr-required, release-note-required

#2300 bpf: Binary.PatchIPv4() logs incorrectly if not IPv4
  bpf/binary.go
Labels: docs-pr-required, release-note-required

#2304 [v3.14] Add local throw routes to wireguard table
  wireguard/wireguard.go
  wireguard/wireguard_test.go
Labels: docs-pr-required, release-note-required

#2307 [v3.14] Backport fix of conntrack deletion
  netlink/mock/netlink.go
  routetable/route_table.go
  routetable/route_table_test.go
Labels: docs-not-required, release-note-not-required

#2309 Update libcalico-go and typha pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2282 changes to support ICMP type and code check in policy in bpf mode
  Makefile
  bpf-gpl/jump.h
  bpf-gpl/tc.c
  bpf/polprog/pol_prog_builder.go
  bpf/polprog/pol_prog_builder_test.go
  bpf/ut/pol_prog_test.go
  rules/policy.go
Labels: docs-pr-required, release-note-required

#2313 Return os.ErrNotExists from map deletes.
  bpf/maps.go
  bpf/ut/maps_test.go
Labels: docs-not-required, release-note-required

#2303 Update of libcalico-go
  daemon/daemon.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2289 WireGuard FV
  .semaphore/create-test-vm
  .semaphore/semaphore.yml
  Makefile
  fv/Dockerfile.test.amd64
  fv/Dockerfile.wgtool.amd64
  fv/wireguard_test.go
Labels: docs-not-required, release-note-not-required

#2316 Reduce cases where we flap BPF programs, improve diags
  bpf/maps.go
  bpf/tc/attach.go
  bpf/ut/maps_test.go
  dataplane/linux/bpf_ep_mgr.go
Labels: docs-not-required, release-note-required

#2322 Revert "WireGuard FV"
  .semaphore/create-test-vm
  .semaphore/semaphore.yml
  Makefile
  fv/Dockerfile.test.amd64
  fv/Dockerfile.wgtool.amd64
  fv/wireguard_test.go
Labels: docs-pr-required, release-note-required

#2324 Updated RecvMessage, payload.WireguardStatusUpdate
  dataplane/external/ext_dataplane.go
Labels: docs-pr-required, release-note-required

#2311 Filter netlink address updates to avoid flapping when an IP is replaced.
  ifacemonitor/iface_monitor.go
  ifacemonitor/ifacemonitor_test.go
  ifacemonitor/update_filter.go
  ifacemonitor/update_filter_test.go
  time/mock/time.go
  time/time.go
Labels: docs-not-required, release-note-required

#2315 Drop packets with IP options
  bpf-gpl/reasons.h
  bpf-gpl/tc.c
  bpf/ut/ip_options_test.go
Labels: docs-pr-required, release-note-required

#2321 Changes to use syscall version for deleting BPF maps
  Makefile
  bpf/bpf_syscall.go
  bpf/maps.go
  bpf/ut/maps_test.go
  cmd/calico-bpf/commands/conntrack.go
Labels: docs-pr-required, release-note-required

#2317 BPF: VXLAN tunnel source/dest policing
  bpf-gpl/conntrack.h
  bpf-gpl/jump.h
  bpf-gpl/tc.c
  bpf/conntrack/map.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/nat_test.go
Labels: docs-pr-required, release-note-required

#2323 Only program iptables chains that are referenced.
  dataplane/linux/policy_mgr.go
  iptables/actions.go
  iptables/table.go
  iptables/table_test.go
Labels: docs-not-required, release-note-required

#2320 Fixing WireGuard flakes
  .semaphore/create-test-vm
  .semaphore/semaphore.yml
  Makefile
  fv/Dockerfile.test.amd64
  fv/Dockerfile.wgtool.amd64
  fv/wireguard_test.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2314 BPF: multi nic rpf fix
  bpf-gpl/bpf.h
  bpf-gpl/list-ut-objs
  bpf-gpl/nat.h
  bpf-gpl/tc.c
  bpf/ut/nat_test.go
  dataplane/linux/int_dataplane.go
  fv/bpf_test.go
Labels: docs-pr-required, release-note-required

#2325 bpf: Proxy healthCheckNodeport unittest
  bpf/proxy/health_check_nodeport_test.go
  bpf/proxy/proxy_test.go
Labels: docs-pr-required, release-note-required

#2328 Fixing build issues with bpf
  bpf-gpl/tc.c
Labels: docs-pr-required, release-note-required

#2326 BPF: decap vxlan iff for any known localhost IP
  bpf-gpl/routes.h
  bpf-gpl/tc.c
  bpf/ut/bpf_prog_test.go
  bpf/ut/nat_test.go
Labels: docs-pr-required, release-note-required

#2329 Disable accept_ra in workloads
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/endpoint_mgr_test.go
Labels: docs-not-required, release-note-not-required

#2327 Git pre-commit check for license, copyright in .c and .h files
  bpf-apache/redir.c
  bpf-gpl/sendrecv.h
  bpf-gpl/ut/icmp_too_big.c
  bpf-gpl/ut/icmp_ttl_exceeded.c
  bpf-gpl/ut/ip_dec_ttl.c
  bpf-gpl/ut/nat_decap_test.c
  bpf-gpl/ut/nat_encap_test.c
  bpf-gpl/ut/ut.h
  dataplane/external/ext_dataplane.go
  git-hooks/pre-commit-in-container
Labels: docs-not-required, release-note-not-required

#2330 Felix WireGuard FVs
  fv/wireguard_test.go
Labels: docs-pr-required, release-note-required

#2336 Add Kubernetes API server port (6443) to failsafes
  config/config_params.go
  config/config_params_test.go
  fv/connectivity/conncheck.go
  fv/hostendpoints_test.go
  fv/infrastructure/infra_k8s.go
  fv/test-connection/test-connection.go
Labels: docs-completed, release-note-required

#2335 Minor FV fixes/improvements
  docker-image/calico-felix-wrapper
  fv/infrastructure/felix.go
Labels: docs-not-required, release-note-not-required

#2334 Fix logging
  dataplane/linux/endpoint_mgr.go
Labels: docs-not-required, release-note-not-required

#2340 Automated cherry pick of #2329: Disable accept_ra in workloads #2334: Only log on err
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/endpoint_mgr_test.go
Labels: docs-not-required, release-note-not-required

#2341 Automated cherry pick of #2340: Disable accept_ra in workloads
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/endpoint_mgr_test.go
Labels: docs-not-required, release-note-not-required

#2343 Automated cherry pick of #2342: Disable accept_ra in workloads
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/endpoint_mgr_test.go
Labels: docs-not-required, release-note-not-required

#2342 Automated cherry pick of #2341: Disable accept_ra in workloads
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/endpoint_mgr_test.go
Labels: docs-not-required, release-note-not-required

#2346 Automated cherry pick of #2345: Disable accept_ra in workloads
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/endpoint_mgr_test.go
Labels: docs-not-required, release-note-not-required

#2345 Automated cherry pick of #2344: Disable accept_ra in workloads
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/endpoint_mgr_test.go
Labels: docs-not-required, release-note-not-required

#2344 Automated cherry pick of #2343: Disable accept_ra in workloads
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/endpoint_mgr_test.go
Labels: docs-not-required, release-note-not-required

#2339 When starting the metric server, only retry the ListenAndServe.
  daemon/daemon.go
Labels: docs-not-required, release-note-required

#2349 Merge pull request #2336 from neiljerram/default-allow-port-6443
  config/config_params.go
  config/config_params_test.go
  fv/connectivity/conncheck.go
  fv/hostendpoints_test.go
  fv/infrastructure/infra_k8s.go
  fv/test-connection/test-connection.go
Labels: docs-completed, release-note-required

#2348 Address WireGuard FV flakes
  fv/wireguard_test.go
Labels: docs-not-required, release-note-not-required

#2337 Fix automatic disabling of BPF mode on older kernels
  bpf/bpf.go
  config/config_params.go
  config/config_params_test.go
  daemon/daemon.go
Labels: docs-pr-required, release-note-required

#2352 bpf/proxy: collect stale UDP services
  bpf/proxy/proxy.go
  bpf/proxy/proxy_test.go
Labels: docs-pr-required, release-note-required

#2338 Connect directly to Typha rather than via ClusterIP
  daemon/daemon.go
  daemon/daemon_test.go
Labels: docs-not-required, release-note-required

#2351 Update of libcalico-go to use new CRDs
  .gitignore
  Makefile
  fv/infrastructure/infra_k8s.go
  fv/utils/utils.go
  go.mod
  go.sum
  k8sfv/run-test
Labels: docs-not-required, release-note-not-required

#2347 bpf: HOST_IP represents the same node ip on all host ifaces
  bpf-gpl/tc.c
  dataplane/linux/bpf_ep_mgr.go
  dataplane/linux/int_dataplane.go
  fv/bpf_test.go
Labels: docs-not-required, release-note-required

#2331 bpf: EndpointSlices support for kube-proxy
  bpf/proxy/options.go
  bpf/proxy/proxy.go
  bpf/proxy/proxy_test.go
  config/config_params.go
  dataplane/driver.go
  dataplane/linux/int_dataplane.go
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required
