Repository projectcalico/felix, pull requests merged in 2020-04, with the labels that each got.

#2246 Default to running tests sequentially.
  Makefile
Labels: docs-pr-required, release-note-required

#2244 Use v3 validator for v3 resources
  calc/validation_filter.go
Labels: docs-not-required, release-note-not-required

#2249 Lower log level on non-error
  daemon/daemon.go
Labels: docs-not-required, release-note-not-required

#2248 Increase semaphore v2 time limit.
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#2250 bpf: fix endianess of state->{sd}port for encap traffic
  bpf-gpl/tc.c
Labels: docs-pr-required, release-note-required

#2228 Normal policy support for host-* endpoints
  dataplane/linux/endpoint_mgr.go
  fv/apply_on_forward_test.go
  fv/host_port_test.go
  fv/hostendpoints_test.go
  fv/infrastructure/infra_etcd.go
  fv/infrastructure/infra_k8s.go
  fv/infrastructure/infrastructure.go
  fv/ipip_test.go
  fv/named_ports_test.go
  fv/vxlan_test.go
  rules/dispatch.go
  rules/dispatch_test.go
  rules/endpoints.go
  rules/rule_defs.go
Labels: docs-pr-required, release-note-required

#2245 Handle route map calculation corner cases
  calc/calc_graph.go
  calc/calc_graph_fv_test.go
  calc/event_sequencer.go
  calc/l3_route_resolver.go
  calc/resources_for_test.go
  calc/states_for_test.go
  calc/vxlan_resolver.go
  dataplane/linux/bpf_route_mgr.go
  dataplane/linux/vxlan_mgr.go
  dataplane/linux/vxlan_mgr_test.go
  dataplane/mock/mock_dataplane.go
  ip/ip_addr.go
  ip/ip_addr_test.go
  ip/trie.go
  proto/felixbackend.pb.go
  proto/felixbackend.proto
Labels: docs-not-required, release-note-required

#2254 Fix handling of local WEP routes.
  calc/calc_graph_fv_test.go
  calc/l3_route_resolver.go
  calc/states_for_test.go
  proto/felixbackend.pb.go
Labels: docs-pr-required, release-note-required

#2255 Rebase BPF route manager onto new route format
  bpf-gpl/routes.h
  bpf/routes/map.go
  dataplane/linux/bpf_route_mgr.go
  fv/bpf_test.go
Labels: docs-not-required, release-note-not-required

#2251 BPF: tunnel MTU configurable via VXLAN MTU
  bpf-gpl/Makefile
  bpf-gpl/bpf.h
  bpf-gpl/calculate-flags
  bpf-gpl/icmp.h
  bpf-gpl/list-ut-objs
  bpf-gpl/nat.h
  bpf-gpl/tc.c
  bpf-gpl/ut/nat_encap_test.c
  bpf/binary.go
  bpf/tc/attach.go
  bpf/ut/attach_test.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/icmp_too_big_test.go
  bpf/ut/precompilation_test.go
  dataplane/linux/bpf_ep_mgr.go
Labels: docs-pr-required, release-note-required

#2253 fv: docker test image
  Makefile
  docker-image/Dockerfile.amd64
  fv/Dockerfile.test.amd64
  fv/conncheck_test.go
  fv/containers/containers.go
  fv/tcpdump/tcpdump.go
  fv/workload/workload.go
Labels: docs-pr-required, release-note-required

#2239 Update go-build to v0.37
  Makefile
Labels: docs-not-required, release-note-not-required

#2260 Fix VXLAN race condition
  bpf/ut/bpf_prog_test.go
  calc/vxlan_resolver.go
Labels: docs-not-required, release-note-required

#2261 Disable unprivileged BPF mode by default.
  calc/profile_decoder.go
  config/config_params.go
  dataplane/driver.go
  dataplane/linux/bpf_route_mgr.go
  dataplane/linux/int_dataplane.go
  fv/bpf_test.go
  fv/infrastructure/infra_k8s.go
  fv/workload/workload.go
  go.mod
  go.sum
  k8sfv/pod.go
Labels: docs-completed, release-note-required

#2263 In BPF mode, add bpf to cluster type
  usagerep/usagerep.go
  usagerep/usagerep_test.go
Labels: docs-not-required, release-note-not-required

#2256 Update routetable to accept deltas
  dataplane/linux/int_dataplane.go
  dataplane/linux/vxlan_mgr.go
  netlink/mock/netlink.go
  netlink/netlink.go
  routetable/dataplane_shims.go
  routetable/route_table.go
  routetable/route_table_test.go
  time/mock/time.go
  time/time.go
Labels: docs-pr-required, release-note-required

#2267 Bump libcalico
  Makefile
  config/config_params_test.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2247 ICMP errors generated by tracked flows treated as related traffic
  bpf-gpl/conntrack.h
  bpf-gpl/icmp.h
  bpf-gpl/skb.h
  bpf-gpl/tc.c
  bpf/ut/bpf_prog_test.go
  bpf/ut/icmp_related_test.go
  fv/bpf_test.go
  fv/containers/containers.go
  fv/infrastructure/felix.go
  fv/tcpdump/tcpdump.go
  fv/workload/workload.go
Labels: docs-not-required, release-note-required

#2269 Configurable source for routing information
  calc/calc_graph.go
  calc/calc_graph_fv_test.go
  calc/l3_route_resolver.go
  calc/resources_for_test.go
  calc/states_for_test.go
  config/config_params.go
  config/config_params_test.go
  fv/vxlan_test.go
Labels: docs-pr-required, release-note-required

#2271 Test static arp invocations
  netlink/mock/netlink.go
  routetable/route_table.go
  routetable/route_table_test.go
Labels: docs-pr-required, release-note-required

#2272 Revert "Merge pull request #2264 from lmm/update-dockerfile"
  docker-image/Dockerfile.amd64
  docker-image/centos.repo
  docker-image/licenses/aplv2
  docker-image/licenses/gpl
  fv/Dockerfile.test.amd64
  fv/latency_test.go
  fv/xdp_test.go
Labels: docs-not-required, release-note-not-required

#2268 Implement routing table config and manager
  config/config_params.go
  config/config_params_test.go
  config/param_types.go
  dataplane/driver.go
  dataplane/linux/int_dataplane.go
  go.mod
  go.sum
  idalloc/index_allocator.go
  idalloc/index_allocator_test.go
Labels: docs-not-required, release-note-not-required

#2274 Make sure we safely take a pointer of the target
  routetable/route_table.go
  routetable/route_table_test.go
Labels: docs-pr-required, release-note-required

#2275 test: fix static check in routetable
  routetable/route_table_test.go
Labels: docs-pr-required, release-note-required

#2270 RPF check
  Makefile
  bpf-gpl/bpf.h
  bpf-gpl/conntrack.h
  bpf-gpl/tc.c
  bpf/conntrack/conntrack_test.go
  bpf/conntrack/map.go
  dataplane/linux/int_dataplane.go
  fv/Dockerfile.test.amd64
  fv/bpf_test.go
  fv/pktgen/pktgen.go
  iptables/match_builder.go
  rules/static.go
  rules/static_test.go
Labels: docs-not-required, release-note-required

#2276 Makefile: always rebuild image if there are changes
  Makefile
Labels: docs-pr-required, release-note-required

#2278 Remove accidental libcalico-go pin from personal repo
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2280 Optimize for route lookups by node in l3 route resolver
  calc/l3_route_resolver.go
Labels: docs-not-required, release-note-not-required

#2277 BPF map versioning
  bpf-gpl/bpf.h
  bpf-gpl/connect_balancer.c
  bpf-gpl/connect_balancer_v6.c
  bpf-gpl/conntrack.h
  bpf-gpl/jump.h
  bpf-gpl/nat.h
  bpf-gpl/policy.h
  bpf-gpl/routes.h
  bpf-gpl/sendrecv.h
  bpf-gpl/tc.c
  bpf/conntrack/map.go
  bpf/maps.go
  fv/bpf_test.go
Labels: docs-pr-required, release-note-required

#2279 Fix logging when VXLAN device doesn't exist.
  dataplane/linux/int_dataplane.go
Labels: docs-not-required, release-note-not-required

#2257 Add wireguard encryption support
  calc/calc_graph.go
  calc/dataplane_passthru.go
  calc/event_sequencer.go
  calc/l3_route_resolver.go
  calc/profile_decoder_test.go
  config/config_params.go
  daemon/daemon.go
  dataplane/driver.go
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/modprobe.go
  dataplane/linux/vxlan_mgr.go
  dataplane/linux/wireguard_mgr.go
  go.mod
  go.sum
  idalloc/index_allocator.go
  netlink/errors.go
  netlink/mock/netlink.go
  netlink/mock/wireguard.go
  netlink/wireguard.go
  proto/felixbackend.pb.go
  proto/felixbackend.proto
  routetable/route_table.go
  wireguard/config.go
  wireguard/wireguard.go
  wireguard/wireguard_suite_test.go
  wireguard/wireguard_test.go
Labels: docs-pr-required, release-note-required

#2281 bpf: simplify whitelisting and test it
  bpf-gpl/conntrack.h
  bpf-gpl/tc.c
  bpf/ut/bpf_prog_test.go
  bpf/ut/nat_test.go
  bpf/ut/whitelist_test.go
Labels: docs-pr-required, release-note-required

#2283 bpf: do not override fib=false if no forward
  bpf-gpl/tc.c
Labels: docs-pr-required, release-note-required

#2284 Auto-configure the IPv4/6 forwarding sysctls.
  dataplane/linux/int_dataplane.go
Labels: docs-not-required, release-note-required

#2285 Add rule manager
  routerule/dataplane_shims.go
  routerule/route_rule.go
  routerule/route_rule_test.go
  routerule/routerule_suite_test.go
  routerule/rule_lib.go
  routerule/rule_lib_test.go
Labels: docs-pr-required, release-note-required

#2287 Add a kernel version check for BPF mode.
  bpf/bpf.go
  config/config_params.go
  config/config_params_test.go
  daemon/daemon.go
Labels: cherry-pick-candidate, docs-not-required, release-note-required
