Repository projectcalico/felix, pull requests merged in 2020-09, with the labels that each got.

#2484 Add knobs to disable adding encap drop rules from workloads
  config/config_params.go
  dataplane/driver.go
  dataplane/linux/endpoint_mgr_test.go
  go.mod
  go.sum
  rules/endpoints.go
  rules/endpoints_test.go
  rules/rule_defs.go
Labels: cherry-pick-candidate, docs-pr-required, release-note-required

#2487 [release-v3.15] cherrypick: Add knobs to disable adding encap drop rules from workloads (#2484)
  config/config_params.go
  dataplane/driver.go
  dataplane/linux/endpoint_mgr_test.go
  go.mod
  go.sum
  rules/endpoints.go
  rules/endpoints_test.go
  rules/rule_defs.go
Labels: docs-pr-required, release-note-required

#2486 [release-v3.16] cherrypick: Add knobs to disable adding encap drop rules from workloads (#2484)
  config/config_params.go
  dataplane/driver.go
  dataplane/linux/endpoint_mgr_test.go
  go.mod
  go.sum
  rules/endpoints.go
  rules/endpoints_test.go
  rules/rule_defs.go
Labels: docs-pr-required, release-note-required

#2492 bpf: avoid jump to epilogue in HEP - no policy yet
  bpf-gpl/tc.c
  fv/bpf_test.go
Labels: docs-pr-required, release-note-required

#2491 bpf: harden accept_local using iptables rpfilter
  bpf/tc/tc_defs.go
  dataplane/linux/int_dataplane.go
Labels: docs-pr-required, release-note-required

#2493 Retry BPF_PROG_TEST_RUN on EINTR.
  bpf/bpf_syscall.go
Labels: docs-not-required, release-note-not-required

#2489 In BPF mode, check that the BPF mark bits are assigned.
  dataplane/driver.go
  fv/bpf_test.go
  rules/rule_defs.go
Labels: docs-pr-required, release-note-required

#2495 Fix that broadcast routes weren't filtered out.
  ifacemonitor/iface_monitor.go
  ifacemonitor/update_filter.go
  ifacemonitor/update_filter_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#2496 [v3.16] Fix that broadcast routes weren't filtered out.
  ifacemonitor/iface_monitor.go
  ifacemonitor/update_filter.go
  ifacemonitor/update_filter_test.go
Labels: docs-not-required, release-note-required

#2498 Avoid missing bpf.h problem, often seen with 'make ut'
  Makefile
Labels: docs-pr-required, release-note-required

#2500 Set DatastoreType etcdv3 if EtcdEndpoints or EtcdAddr specified
  config/config_params.go
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2502 Semaphore Auto Pin Update PR
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2503 Add update pins pipelines
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
  Makefile
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2506 Allow semaphore-run-auto-pin-update-workflows to set the SEMAPHORE_PROJECT_ID (only default it if it's not set)
  Makefile
Labels: docs-not-required, release-note-not-required
