Repository projectcalico/felix, pull requests merged in 2020-07, with the labels that each got.

#2410 Allow tc to run in parallel again.
  bpf/binary.go
  bpf/tc/attach.go
  dataplane/linux/bpf_ep_mgr.go
Labels: docs-not-required, release-note-required

#2411 Quieten skipped tests.
  fv/run-batches
Labels: docs-not-required, release-note-not-required

#2408 Add benchmarks for named port index.
  labelindex/named_port_bench_test.go
Labels: docs-not-required, release-note-not-required

#2413 Speed up FV tests
  fv/infrastructure/infra_k8s.go
  fv/infrastructure/topology.go
  fv/utils/utils.go
Labels: docs-not-required, release-note-not-required

#2404 Add FV tests for WireGuard host to workload
  fv/wireguard_test.go
Labels: docs-not-required, release-note-not-required

#2414 Switch from Skip to conditional test definitions.
  fv/bpf_test.go
  fv/infrastructure/infra_k8s.go
Labels: docs-not-required, release-note-not-required

#2400 Run a stripe of BPF tests with Wireguard as well
  fv/bpf_test.go
  fv/infrastructure/topology.go
Labels: docs-not-required, release-note-not-required

#2409 Adding support to detect RHEL with kernel version 4.18.0
  bpf/bpf.go
  bpf/bpf_test.go
  iptables/feature_detect.go
  versionparse/lib.go
Labels: docs-not-required, release-note-required

#2415 Integrate Wireguard FVs into main FV runs, including BPF
  .semaphore/semaphore.yml
  Makefile
  fv/wireguard-available
  fv/wireguard_test.go
Labels: docs-not-required, release-note-not-required

#2418 Do FIB lookup on to-host path.
  bpf-gpl/tc.c
Labels: docs-pr-required, release-note-required

#2419 Add more jobs to new-kernel FVs and reduce normal FVs.
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required

#2420 Squash spammy wireguard log.
  wireguard/wireguard.go
Labels: docs-not-required, release-note-required

#2310 Allow override of iptable features like "MASQFullyRandom"
  config/config_params.go
  config/param_types.go
  config/param_types_test.go
  dataplane/driver.go
  dataplane/linux/int_dataplane.go
  go.mod
  go.sum
  iptables/feature_detect.go
  iptables/features_detect_test.go
  iptables/rules_test.go
  iptables/table_test.go
  stringutils/parse_keyvalue_list.go
  stringutils/parse_keyvalue_list_test.go
Labels: docs-pr-required, release-note-required

#2417 Support for both appending and inserting chains in iptables dataplane
  dataplane/linux/int_dataplane.go
  dataplane/linux/int_dataplane_test.go
  iptables/actions.go
  iptables/actions_test.go
  iptables/table.go
  iptables/table_test.go
  rules/nat_test.go
  rules/static.go
Labels: docs-not-required, release-note-not-required

#2381 Add AWS source-destination-check handling
  aws/ec2.go
  aws/ec2_suite_test.go
  aws/ec2_test.go
  dataplane/driver.go
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2427 Rename shims to avoid name clashes
  bpf/proxy/service_type_change_test.go
  dataplane/linux/bpf_ep_mgr.go
  ifacemonitor/update_filter.go
  ifacemonitor/update_filter_test.go
  netlink/errors.go
  netlinkshim/errors.go
  netlinkshim/mocknetlink/netlink.go
  netlinkshim/mocknetlink/wireguard.go
  netlinkshim/netlink.go
  netlinkshim/wireguard.go
  routetable/route_table.go
  routetable/route_table_test.go
  timeshim/mocktime/mocktime.go
  timeshim/time.go
  wireguard/wireguard.go
  wireguard/wireguard_test.go
Labels: docs-not-required, release-note-not-required

#2429 Only enable verifier log for post-failure retry
  bpf/bpf_syscall.go
  bpf/ut/pol_prog_test.go
Labels: docs-not-required, release-note-required

#2428 Rate limit jump map cleanup
  dataplane/linux/bpf_ep_mgr.go
  fv/apply_on_forward_test.go
  fv/bpf_test.go
  fv/host_port_test.go
  fv/hostendpoints_test.go
  fv/infrastructure/infra_etcd.go
  fv/infrastructure/infra_k8s.go
  fv/infrastructure/infrastructure.go
  fv/ipip_test.go
  fv/pre_dnat_test.go
  fv/sockmap_test.go
  fv/spoof_test.go
  fv/vxlan_test.go
  fv/wireguard_test.go
  fv/workload/workload.go
  ratelimited/runner.go
  ratelimited/runner_test.go
  timeshim/mocktime/mocktime.go
  timeshim/time.go
Labels: docs-not-required, release-note-required

#2423 Drop packets to unknown WEPs
  bpf-gpl/bpf.h
  bpf-gpl/conntrack.h
  bpf-gpl/list-ut-objs
  bpf/bpf_syscall.go
  bpf/tc/tc_defs.go
  bpf/ut/nat_test.go
  bpf/ut/pol_prog_test.go
  bpf/ut/whitelist_test.go
  dataplane/linux/bpf_ep_mgr.go
  dataplane/linux/int_dataplane.go
  fv/bpf_test.go
  fv/tcpdump/tcpdump.go
  rules/dispatch.go
  rules/nat.go
  rules/rule_defs.go
Labels: docs-not-required, release-note-required

#2424 Move policy acceptance to end of the filter table forward chain
  dataplane/linux/int_dataplane.go
  rules/rule_defs.go
  rules/static.go
  rules/static_test.go
Labels: docs-not-required, release-note-required

#2432 Test fix: wait longer for jump map cleanup.
  fv/bpf_test.go
Labels: docs-not-required, release-note-not-required

#2433 Add config param to control the interface monitor's resync interval.
  config/config_params.go
  dataplane/driver.go
  dataplane/linux/bpf_ep_mgr.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/int_dataplane_test.go
  go.mod
  go.sum
  ifacemonitor/iface_monitor.go
Labels: docs-pr-required, release-note-required

#2431 Fix BPF endpoint manager handling of endpoint recreation
  bpf/tc/attach.go
  dataplane/linux/bpf_ep_mgr.go
  dataplane/linux/int_dataplane.go
  fv/bpf_test.go
Labels: docs-not-required, release-note-required

#2435 WG fv test fixes and bpf code simplifications
  bpf-gpl/bpf.h
  bpf-gpl/skb.h
  bpf-gpl/tc.c
  bpf/ut/precompilation_test.go
  fv/bpf_test.go
  fv/infrastructure/infra_k8s.go
  fv/infrastructure/topology.go
Labels: docs-pr-required, release-note-required

#2438 Changes to fix wireguard ci failure
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required

#2437 Upgrade to golang 1.14
  .golangci.yaml
  Makefile
  bpf/polprog/pol_prog_builder.go
  fv/xdp_test.go
  go.mod
  go.sum
  proto/felixbackend.pb.go
Labels: docs-not-required, release-note-required

#2436 Handling LoadBalancerIPStrings as a derived service
  bpf/proxy/lb_src_range_test.go
  bpf/proxy/service_type_change_test.go
  bpf/proxy/syncer.go
Labels: docs-pr-required, release-note-required
