Repository projectcalico/felix, pull requests merged in 2020-03, with the labels that each got.

#2223 Send ICMP too bigs directly
  bpf-gpl/bpf.h
  bpf-gpl/icmp.h
  bpf-gpl/nat.h
  bpf-gpl/skb.h
  bpf-gpl/tc.c
Labels: docs-not-required, release-note-not-required

#2224 add goreportcard to README
  README.md
Labels: docs-not-required, release-note-not-required

#2225 Fix misspellings reported by goreport
  bpf/asm/asm.go
  bpf/bpf.go
  bpf/nat/maps.go
  bpf/proxy/syncer.go
  dataplane/linux/vxlan_mgr.go
  fv/bpf_test.go
  fv/policysync_test.go
  k8sfv/monitoring.md
  rules/policy.go
Labels: docs-pr-required, release-note-required

#2226 Implement GC of cali_jump maps.
  bpf/tc/attach.go
  bpf/ut/attach_test.go
  dataplane/linux/bpf_ep_mgr.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#2227 [v3.13] Clean up jump maps
  bpf/tc/attach.go
  bpf/ut/attach_test.go
  dataplane/linux/bpf_ep_mgr.go
Labels: docs-not-required, release-note-not-required

#2229 BPF: MTU fix for 3.13
  bpf-gpl/icmp.h
  bpf-gpl/nat.h
  bpf-gpl/tc.c
  bpf/ut/icmp_too_big_test.go
  bpf/ut/nat_test.go
Labels: docs-pr-required, release-note-required

#2230 backport of to 3.13 PR 2229 BPF: MTU fix for 3.13
  bpf-gpl/icmp.h
  bpf-gpl/nat.h
  bpf-gpl/tc.c
  bpf/ut/icmp_too_big_test.go
  bpf/ut/nat_test.go
Labels: docs-not-required, release-note-required

#2232 bpf: fix GSO handling on the host side of NP
  bpf-gpl/tc.c
Labels: docs-not-required, release-note-required

#2233 bpf: fix FIB lookup for NP tunnels and ICMP error replies
  bpf-gpl/jump.h
  bpf-gpl/tc.c
Labels: docs-pr-required, release-note-required

#2235 Remove unused constant
  bpf/ut/bpf_prog_test.go
Labels: docs-pr-required, release-note-required

#2236 report k8s version
  daemon/daemon.go
  usagerep/usagerep.go
  usagerep/usagerep_test.go
Labels: docs-pr-required, release-note-required

#2237 Beef up FV test infrastructure.
  bpf/tc/attach.go
  fv/bpf_test.go
  fv/config_update_test.go
  fv/conncheck_test.go
  fv/connectivity/conncheck.go
  fv/containers/containers.go
  fv/containers/tcpdump.go
  fv/etcd_restart_test.go
  fv/host_port_test.go
  fv/infrastructure/felix.go
  fv/infrastructure/infra_etcd.go
  fv/infrastructure/infra_k8s.go
  fv/infrastructure/infrastructure.go
  fv/infrastructure/topology.go
  fv/infrastructure/typha.go
  fv/ingress_egress_test.go
  fv/ipip_test.go
  fv/metrics/metrics.go
  fv/named_ports_test.go
  fv/netsets_test.go
  fv/policysync_test.go
  fv/test-connection/test-connection.go
  fv/test-workload/test-workload.go
  fv/utils/utils.go
  fv/workload/workload.go
  usagerep/usagerep.go
  usagerep/usagerep_test.go
Labels: docs-not-required, release-note-not-required

#2238 BPF: check the VNI of the VXLAN NP tunnel
  bpf-gpl/nat.h
  bpf-gpl/tc.c
  bpf/ut/nat_encap_test.go
  bpf/ut/nat_test.go
Labels: docs-pr-required, release-note-required

#2234 FV test for MTU adjustments with bpf NP tunnels
  docker-image/Dockerfile.amd64
  fv/bpf_test.go
  fv/connectivity/conncheck.go
  fv/containers/containers.go
  fv/test-connection/test-connection.go
  fv/test-workload/test-workload.go
  fv/utils/utils.go
  fv/workload/workload.go
Labels: docs-pr-required, release-note-required

#2240 Set log component for additional context
  fv/test-connection/test-connection.go
  fv/test-workload/test-workload.go
  fv/workload/workload.go
  go.mod
  go.sum
  logutils/logutils.go
Labels: docs-not-required, release-note-not-required

#2241 Remove duplicate BPF enabled check.
  dataplane/linux/endpoint_mgr.go
Labels: docs-not-required, release-note-not-required
