Repository projectcalico/felix, pull requests merged in 2021-05, with the labels that each got.

#2795 Retry setting AWS EC2 src-dst-check until successful
  aws/ec2.go
  aws/ec2_test.go
  dataplane/driver.go
Labels: docs-not-required, merge-when-ready, release-note-required, squash-commits

#2802 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2806 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2807 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2808 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2810 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2812 Fix bpf logs
  bpf/tc/attach.go
  dataplane/linux/bpf_ep_mgr.go
  dataplane/linux/bpf_ep_mgr_test.go
  dataplane/linux/bpf_route_mgr.go
  dataplane/linux/int_dataplane.go
  fv/wireguard_test.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#2814 Reduce FV verbosity
  fv/containers/containers.go
  fv/infrastructure/infra_etcd.go
  fv/infrastructure/infra_k8s.go
  fv/named_ports_test.go
  fv/utils/utils.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#2816 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2818 Fix ip rule logic to stop churning rules
  fv/wireguard_test.go
  routerule/route_rule.go
  wireguard/wireguard.go
  wireguard/wireguard_test.go
Labels: docs-pr-required, release-note-required

#2819 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2815 [v3.19] Backport VXLAN checksum fix
  .semaphore/create-test-vm
  .semaphore/semaphore.yml
  dataplane/linux/int_dataplane.go
  dataplane/linux/vxlan_mgr.go
  dataplane/linux/vxlan_mgr_test.go
  ethtool/ethtool.go
  fv/bpf_test.go
  fv/containers/containers.go
  fv/infrastructure/infra_etcd.go
  fv/infrastructure/infra_k8s.go
  fv/named_ports_test.go
  fv/utils/utils.go
  fv/vxlan_test.go
  fv/wireguard_test.go
  go.mod
  go.sum
  iptables/feature_detect.go
  iptables/features_detect_test.go
Labels: docs-pr-required, release-note-required

#2821 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2823 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2824 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2825 Swap out unmaintained UUID library for Google one.
  dataplane/linux/vxlan_mgr.go
  fv/connectivity/conncheck.go
  fv/test-connection/test-connection.go
  fv/utils/utils.go
  go.mod
  go.sum
Labels: docs-pr-required, merge-when-ready, release-note-required

#2828 Small improvements to BPF C coding
  bpf-gpl/conntrack.h
  bpf-gpl/conntrack_types.h
  bpf-gpl/tc.c
Labels: docs-not-required, release-note-not-required

#2827 DebugBPFMapRepinEnabled -> false
  config/config_params.go
  fv/infrastructure/felix.go
Labels: docs-not-required, release-note-required

#2820 Stop ARP traffic being dropped due to RPF check
  dataplane/linux/int_dataplane.go
  fv/wireguard_test.go
  rules/rule_defs.go
  rules/static.go
  rules/static_test.go
Labels: docs-pr-required, release-note-required

#2822 Use new common cd formatting / pipeline
  .semaphore/semaphore.yml
  Makefile
Labels: docs-not-required, release-note-not-required

#2826 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2829 BPF coding markups
  bpf-gpl/conntrack.h
Labels: docs-not-required, release-note-not-required

#2831 BPF: Simplify CT context code
  bpf-gpl/conntrack.h
  bpf-gpl/conntrack_types.h
  bpf-gpl/tc.c
Labels: docs-not-required, release-note-not-required

#2696 CORE-4739 | Install blackhole routes in VXLAN mode
  dataplane/linux/vxlan_mgr.go
  dataplane/linux/vxlan_mgr_test.go
  fv/infrastructure/topology.go
  fv/vxlan_test.go
Labels: docs-not-required, release-note-required

#2834 FV: Make a separate copy of TopologyOptions for each Felix
  fv/infrastructure/topology.go
Labels: docs-not-required, release-note-not-required

#2832 Wireguard fv handshake wait
  fv/test-workload/test-workload.go
  fv/wireguard_test.go
  fv/workload/workload.go
  rules/static.go
Labels: docs-pr-required, release-note-required

#2835 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
