Repository projectcalico/felix, pull requests merged in 2021-06, with the labels that each got.

#2837 Ignore /32 routes when programming VXLAN blackhole routes.
  dataplane/linux/vxlan_mgr.go
  dataplane/linux/vxlan_mgr_test.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#2838 Apply BPF TC program to vxlan.calico devices
  config/config_params.go
Labels: docs-not-required, release-note-not-required

#2839 Make CALI_ST constants easier to identify when debugging
  bpf-gpl/types.h
Labels: docs-pr-required, release-note-required

#2841 add ip_size to cali_tc_state struct
  bpf-gpl/jump.h
  bpf-gpl/types.h
  bpf/state/map.go
Labels: docs-not-required, release-note-not-required

#2840 Wireguard MTU calculation on AKS and ANI allows for underlying network
  config/config_params.go
  config/config_params_test.go
  dataplane/driver.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/int_dataplane_test.go
Labels: docs-pr-required, release-note-required

#2842 UT: Run following UT suites when one suite fails
  utils/run-coverage
Labels: docs-not-required, release-note-not-required

#2843 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2844 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2847 Replace lib/v3 package with projectcalico/api
  aws/ec2.go
  calc/calc_graph.go
  calc/calc_graph_test.go
  calc/dataplane_passthru.go
  calc/event_sequencer.go
  calc/l3_route_resolver.go
  calc/profile_decoder_test.go
  calc/resources_for_test.go
  calc/rule_convert.go
  calc/rule_convert_test.go
  calc/rule_scanner.go
  calc/rule_scanner_test.go
  calc/states_for_test.go
  calc/vxlan_resolver.go
  config/config_params.go
  config/config_params_test.go
  config/param_types.go
  daemon/daemon.go
  dataplane/driver.go
  fv/apply_on_forward_test.go
  fv/bpf_test.go
  fv/config_update_test.go
  fv/donottrack_test.go
  fv/etcd_restart_test.go
  fv/health_test.go
  fv/host_port_test.go
  fv/hostendpoints_test.go
  fv/infrastructure/infra_etcd.go
  fv/infrastructure/infra_k8s.go
  fv/infrastructure/infrastructure.go
  fv/infrastructure/topology.go
  fv/ingress_egress_test.go
  fv/ipip_test.go
  fv/latency_test.go
  fv/mtu_test.go
  fv/named_ports_test.go
  fv/nat_outgoing_test.go
  fv/netsets_test.go
  fv/policysync_test.go
  fv/pre_dnat_test.go
  fv/rule_metadata_test.go
  fv/service_loop_prevention_test.go
  fv/utils/utils.go
  fv/vxlan_test.go
  fv/wireguard_test.go
  fv/xdp_test.go
  go.mod
  go.sum
  labelindex/named_port_index.go
  rules/nat_test.go
  rules/rule_defs.go
  rules/static_test.go
Labels: docs-pr-required, release-note-required

#2849 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2851 Fix sem timeouts and priorities
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#2854 Reduce organisation impact of semaphore job
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#2856 Combine bpf fvs
  .semaphore/collect-artifacts-from-vms
  .semaphore/create-test-vms
  .semaphore/run-tests-on-vms
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#2858 disable unreliable wireguard fv tests
  fv/wireguard_test.go
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#2859 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2861 Tweaks to new parallel FV system
  .semaphore/collect-artifacts
  .semaphore/collect-artifacts-from-vms
  .semaphore/run-tests-on-vms
Labels: docs-not-required, release-note-not-required

#2862 Reduce felix FV log severity; add env var to override for debug
  Makefile
  fv/bpf_test.go
  fv/infrastructure/topology.go
  fv/mtu_test.go
  fv/sockmap_test.go
Labels: docs-pr-required, release-note-required

#2865 BPF: Handle window between BPF_MAP_GET_NEXT_KEY and BPF_MAP_LOOKUP_ELEM
  bpf/bpf_syscall.h
Labels: docs-pr-required, release-note-required

#2864 upgrade clang version from clang-7 to clang-11 for bpf build
  Makefile
  bpf-apache/Makefile
  bpf-gpl/Makefile
Labels: docs-pr-required, release-note-required

#2868 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2867 Update api pins on pin update
  Makefile
Labels: docs-not-required, release-note-not-required

#2870 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2853 basic wireguard prometheus stats
  config/config_params.go
  daemon/daemon.go
  fv/wireguard_test.go
  go.mod
  go.sum
  netlinkshim/mocknetlink/wireguard.go
  netlinkshim/wireguard.go
  wireguard/metrics.go
  wireguard/metrics_test.go
Labels: docs-pr-required, release-note-required

#2872 Added CI job to build calico-felix.exe
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required

#2873 fix wireguard package imported in daemon.go breaking windows build
  daemon/daemon.go
  dataplane/driver.go
  dataplane/driver_windows.go
Labels: docs-pr-required, release-note-required

#2876 Wireguard FV: capture and log wireguard module debugging
  fv/wireguard_test.go
Labels: docs-not-required, release-note-not-required
