Repository projectcalico/felix, pull requests merged in 2021-07, with the labels that each got.

#2878 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2879 Fix XDP FV tests and add them to Semaphore CI
  .semaphore/collect-artifacts-from-vms
  .semaphore/create-test-vms
  .semaphore/new-kernel-common.sh
  .semaphore/run-tests-on-vms
  bpf/bpf.go
  dataplane/linux/xdp_state.go
  fv/xdp_test.go
Labels: delete-branch, docs-pr-required, merge-when-ready, release-note-required

#2880 Fix XDP flake: a check that we cannot reasonably rely on
  .semaphore/create-test-vm
  fv/xdp_test.go
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2881 Convert XDP callback usage to mainline Felix architecture
  dataplane/linux/callbacks.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/ipsets_mgr.go
  dataplane/linux/ipsets_mgr_test.go
  dataplane/linux/policy_mgr.go
  dataplane/linux/policy_mgr_test.go
  dataplane/linux/xdp_state.go
  fv/xdp_test.go
Labels: docs-pr-required, release-note-required

#2884 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2885 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2877 XDP parser
  bpf-gpl/bpf.h
  bpf-gpl/parsing.h
  bpf-gpl/skb.h
  bpf-gpl/tc.c
  bpf-gpl/types.h
  bpf-gpl/xdp.c
Labels: docs-not-required, release-note-not-required

#2886 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2889 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2890 Don't leak tcpdump containers
  fv/containers/containers.go
  fv/tcpdump/tcpdump.go
Labels: docs-not-required, release-note-not-required

#2896 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2892 [master] Semaphore Auto Pin Update
  config/config_params.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2898 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2901 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2900 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2902 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2888 XDP program for untracked policies
  bpf-gpl/jump.h
  bpf-gpl/metadata.h
  bpf-gpl/parsing.h
  bpf-gpl/reasons.h
  bpf-gpl/tc.c
  bpf-gpl/xdp.c
Labels: docs-not-required, release-note-not-required

#2908 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2905 Use XDP to implement untracked deny policies in BPF mode
  bpf-gpl/Makefile
  bpf-gpl/calculate-flags
  bpf-gpl/list-objs
  bpf-gpl/log.h
  bpf/bpf_syscall.go
  bpf/bpf_syscall_stub.go
  bpf/polprog/pol_prog_builder.go
  bpf/tc/attach.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/pol_prog_test.go
  bpf/xdp/attach.go
  dataplane/linux/bpf_ep_mgr.go
  dataplane/linux/bpf_ep_mgr_test.go
  dataplane/linux/int_dataplane.go
  fv/xdp_test.go
Labels: docs-pr-required, release-note-required

#2906 bpf/proxy: Increase timeouts and log the last error
  bpf/proxy/health_check_nodeport_test.go
Labels: docs-pr-required, release-note-required

#2911 Add policy and icmp reply programs to XDP
  bpf-gpl/metadata.h
  bpf-gpl/parsing.h
  bpf-gpl/xdp.c
Labels: docs-not-required, release-note-not-required

#2874 Add ServiceIndex component
  bpf/polprog/pol_prog_builder.go
  bpf/polprog/pol_prog_builder_test.go
  calc/calc_graph.go
  calc/calc_graph_fv_test.go
  calc/resources_for_test.go
  calc/rule_convert.go
  calc/rule_convert_test.go
  calc/rule_scanner.go
  calc/rule_scanner_test.go
  calc/states_for_test.go
  dataplane/driver_windows.go
  dataplane/linux/xdp_state.go
  dataplane/linux/xdp_state_test.go
  dataplane/windows/policysets/policysets.go
  dataplane/windows/policysets/policysets_test.go
  fv/ingress_egress_test.go
  fv/rule_metadata_test.go
  fv/service_policy_test.go
  go.mod
  go.sum
  policysync/ipset.go
  proto/felixbackend.pb.go
  proto/felixbackend.proto
  rules/policy.go
  serviceindex/serviceindex.go
  serviceindex/serviceindex_suite_test.go
  serviceindex/serviceindex_test.go
  wireguard/metrics.go
  wireguard/metrics_test.go
Labels: docs-pr-required, release-note-required

#2915 Cherry picks for v3.20: BPF mode implementation of untracked ingress Deny policy
  bpf-gpl/Makefile
  bpf-gpl/calculate-flags
  bpf-gpl/jump.h
  bpf-gpl/list-objs
  bpf-gpl/log.h
  bpf-gpl/metadata.h
  bpf-gpl/parsing.h
  bpf-gpl/reasons.h
  bpf-gpl/tc.c
  bpf-gpl/xdp.c
  bpf/bpf_syscall.go
  bpf/bpf_syscall_stub.go
  bpf/polprog/pol_prog_builder.go
  bpf/tc/attach.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/pol_prog_test.go
  bpf/xdp/attach.go
  dataplane/linux/bpf_ep_mgr.go
  dataplane/linux/bpf_ep_mgr_test.go
  dataplane/linux/int_dataplane.go
  fv/xdp_test.go
Labels: docs-pr-required, release-note-required

#2916 Automated cherry pick of #2874: Add ServiceIndex component, handle service rules
  bpf/polprog/pol_prog_builder.go
  bpf/polprog/pol_prog_builder_test.go
  calc/calc_graph.go
  calc/calc_graph_fv_test.go
  calc/resources_for_test.go
  calc/rule_convert.go
  calc/rule_convert_test.go
  calc/rule_scanner.go
  calc/rule_scanner_test.go
  calc/states_for_test.go
  dataplane/driver_windows.go
  dataplane/linux/xdp_state.go
  dataplane/linux/xdp_state_test.go
  dataplane/windows/policysets/policysets.go
  dataplane/windows/policysets/policysets_test.go
  fv/ingress_egress_test.go
  fv/rule_metadata_test.go
  fv/service_policy_test.go
  go.mod
  go.sum
  policysync/ipset.go
  proto/felixbackend.pb.go
  proto/felixbackend.proto
  rules/policy.go
  serviceindex/serviceindex.go
  serviceindex/serviceindex_suite_test.go
  serviceindex/serviceindex_test.go
  wireguard/metrics.go
  wireguard/metrics_test.go
Labels: docs-completed, release-note-required

#2922 Update pins
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2924 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2923 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2926 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2925 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2897 Propagate WireguardHostEncryptionEnabled config_param
  dataplane/driver.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/int_dataplane_test.go
  dataplane/linux/wireguard_mgr.go
  rules/rule_defs.go
  rules/static.go
  rules/static_test.go
  wireguard/config.go
  wireguard/wireguard.go
Labels: docs-pr-required, release-note-required

#2919 Avoid race + panic when unnecessarily cleaning up the Kubernetes API service
  fv/infrastructure/infra_k8s.go
Labels: docs-not-required, release-note-not-required

#2913 Rename BPF "epilogue" program to "allowed"
  bpf-gpl/jump.h
  bpf-gpl/policy_program.h
  bpf/polprog/pol_prog_builder.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/pol_prog_test.go
Labels: docs-pr-required, release-note-required

#2920 Some simple backports / alignments from the Enterprise code, mostly BPF
  bpf-gpl/Makefile
  bpf-gpl/bpf.h
  bpf-gpl/connect_balancer.c
  bpf/bpf_syscall.go
  bpf/bpf_syscall_stub.go
  bpf/tc/tc_defs.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/pol_prog_test.go
  dataplane/linux/bpf_ep_mgr.go
  fv/run-batches
  fv/test-list-filter.awk
Labels: docs-not-required, release-note-not-required

#2928 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2930 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2931 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2929 Add UT for the control plane half of BPF mode XDP function
  bpf/ut/pol_prog_test.go
  dataplane/linux/bpf_ep_mgr_test.go
Labels: docs-not-required, release-note-not-required

#2932 Update release targets
  Makefile
Labels: docs-pr-required, release-note-required

#2934 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2936 Update release targets
  Makefile
Labels: docs-not-required, release-note-not-required

#2937 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2938 Fix release target
  Makefile
  bpf/xdp/attach.go
  calc/resources_for_test.go
  fv/service_policy_test.go
  serviceindex/serviceindex_test.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#2918 XDP UT framework
  bpf/ut/benchmarks_test.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/failsafes_test.go
  bpf/ut/icmp_port_unreachable_test.go
  bpf/ut/icmp_related_test.go
  bpf/ut/icmp_ttl_exceeded_test.go
  bpf/ut/ip_options_test.go
  bpf/ut/nat_test.go
  bpf/ut/spoof_test.go
  bpf/ut/to_host_allowed_test.go
  bpf/ut/whitelist_test.go
Labels: docs-not-required, release-note-not-required

#2939 Move generated files above where they are used
  Makefile
Labels: docs-not-required, release-note-not-required

#2941 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2940 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2942 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2943 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required
