Repository projectcalico/felix, pull requests merged in 2021-04, with the labels that each got.

#2751 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2756 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2754 Update libcalico-go to latest version
  bpf/proxy/proxy.go
  bpf/proxy/proxy_test.go
  bpf/proxy/syncer.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2755 Fix for FV failures in l3_route_resolver
  calc/l3_route_resolver.go
  fv/infrastructure/infra_etcd.go
  fv/infrastructure/infra_k8s.go
  fv/infrastructure/infrastructure.go
  fv/ipip_test.go
  fv/vxlan_test.go
  go.mod
  go.sum
Labels: docs-pr-required, release-note-required

#2761 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2762 Clean up Makefile
  Makefile
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2766 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2768 Split up CI to avoid disk issues
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#2758 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2772 Add handling for IPv6 networks in failsafe rules
  config/config_params.go
  config/config_params_test.go
  config/param_types.go
  dataplane/driver.go
  rules/static.go
  rules/static_test.go
Labels: docs-not-required, release-note-required

#2771 Dont panic when we see a sctp named port
  bpf/ipsets/map.go
Labels: docs-pr-required, release-note-required

#2769 Add CIDR handling for failsafes in bpf
  bpf-gpl/failsafe.h
  bpf-gpl/tc.c
  bpf/failsafes/failsafe_test.go
  bpf/failsafes/failsafes.go
  bpf/failsafes/failsafes_map.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/failsafes_test.go
Labels: docs-not-required, release-note-required

#2773 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2767 BPF: RPF check in EKS
  bpf-gpl/bpf.h
  bpf-gpl/conntrack.h
  bpf-gpl/conntrack_types.h
  bpf-gpl/fib.h
  bpf-gpl/tc.c
  bpf/binary.go
  bpf/conntrack/map.go
  bpf/tc/attach.go
  bpf/ut/nat_test.go
  config/config_params.go
  dataplane/driver.go
  dataplane/linux/bpf_ep_mgr.go
  dataplane/linux/bpf_ep_mgr_test.go
  dataplane/linux/int_dataplane.go
  fv/bpf_test.go
  go.mod
  go.sum
  iptables/actions.go
  iptables/match_builder.go
Labels: docs-pr-required, release-note-required

#2775 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2770 Fix handling of overlapping IPs in kube-proxy implementation
  bpf/cachingmap/caching_map.go
  bpf/cachingmap/caching_map_test.go
  bpf/mock/map.go
  bpf/proxy/health_check_nodeport_test.go
  bpf/proxy/kube-proxy.go
  bpf/proxy/lb_src_range_test.go
  bpf/proxy/proxy.go
  bpf/proxy/proxy_bench_test.go
  bpf/proxy/proxy_test.go
  bpf/proxy/service_type_change_test.go
  bpf/proxy/syncer.go
  bpf/proxy/syncer_bench_test.go
  bpf/proxy/syncer_test.go
  fv/bpf_test.go
Labels: docs-not-required, release-note-required

#2776 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2777 bpf: reserve conntrack flags for upgrade compatibility
  bpf-gpl/conntrack_types.h
  bpf/conntrack/map.go
Labels: docs-pr-required, release-note-required

#2778 [v3.18] backport syncer fix
  bpf/cachingmap/caching_map.go
  bpf/cachingmap/caching_map_test.go
  bpf/mock/map.go
  bpf/proxy/health_check_nodeport_test.go
  bpf/proxy/kube-proxy.go
  bpf/proxy/lb_src_range_test.go
  bpf/proxy/proxy.go
  bpf/proxy/proxy_bench_test.go
  bpf/proxy/proxy_test.go
  bpf/proxy/service_type_change_test.go
  bpf/proxy/syncer.go
  bpf/proxy/syncer_bench_test.go
  bpf/proxy/syncer_test.go
  fv/bpf_test.go
Labels: docs-not-required, release-note-required

#2779 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2780 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2782 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2784 Add handling for IPv6 networks in failsafe rules
  config/config_params.go
  config/config_params_test.go
  config/param_types.go
  dataplane/driver.go
  rules/static.go
  rules/static_test.go
Labels: docs-not-required, release-note-required

#2785 Add handling for IPv6 networks in failsafe rules
  config/config_params.go
  config/config_params_test.go
  config/param_types.go
  dataplane/driver.go
  rules/static.go
  rules/static_test.go
Labels: docs-pr-required, release-note-required

#2788 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2790 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2792 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2793 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2787 Reduce log level to debug for selector ID check
  labelindex/label_inheritance_index.go
Labels: docs-not-required, release-note-not-required

#2796 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2798 Service loop prevention for LoadBalancer IPs
  calc/calc_graph_test.go
  calc/event_sequencer.go
  dataplane/linux/service_loop_mgr.go
  fv/service_loop_prevention_test.go
  proto/felixbackend.pb.go
  proto/felixbackend.proto
Labels: docs-not-required, release-note-required
