Repository projectcalico/felix, pull requests merged in 2021-09, with the labels that each got.

#2988 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2989 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2990 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2992 Fix service loop prevention flake
  fv/service_loop_prevention_test.go
Labels: docs-not-required, release-note-not-required

#2991 Don't crash when untracked policy is applied to a host-* endpoint
  dataplane/linux/endpoint_mgr.go
Labels: docs-not-required, release-note-not-required

#2994 XDP tests now run on Semaphore VM
  .semaphore/new-kernel-common.sh
  .semaphore/run-tests-on-vms
  fv/sockmap_test.go
Labels: release-note-required, docs-pr-required

#2986 bugfix: vxlan noencap blackhole contention
  dataplane/linux/vxlan_mgr.go
  routetable/route_table.go
Labels: release-note-required, docs-pr-required

#2997 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2995 [backport] bugfix: vxlan_mgr noencap and blackhole routing table contention
  .semaphore/new-kernel-common.sh
  .semaphore/run-tests-on-vms
  dataplane/linux/vxlan_mgr.go
  fv/sockmap_test.go
  routetable/route_table.go
Labels: release-note-required, docs-not-required

#2983 bpf: source port collision resolution
  bpf-gpl/bpf.h
  bpf-gpl/conntrack.h
  bpf-gpl/conntrack_types.h
  bpf-gpl/nat.h
  bpf-gpl/tc.c
  bpf/binary.go
  bpf/conntrack/map.go
  bpf/tc/attach.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/nat_encap_test.go
  bpf/ut/nat_test.go
  dataplane/linux/bpf_ep_mgr.go
  fv/bpf_test.go
  fv/connectivity/conncheck.go
Labels: release-note-required, docs-pr-required

#2895 Run Windows FV tests
  .semaphore/run-win-fv
  .semaphore/semaphore.yml
  Makefile
  fv/winfv/policy_test.go
  fv/winfv/win_fv_suite_test.go
Labels: docs-not-required, release-note-not-required

#3006 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#3007 [WIP] Backout previous routetable fix and change how we handle empty interface regex
  dataplane/linux/vxlan_mgr.go
  routetable/route_table.go
Labels: release-note-required, docs-pr-required

#3008 Backout previous routetable fix and change how we handle empty interface regex
  dataplane/linux/vxlan_mgr.go
  routetable/route_table.go
Labels: release-note-required, docs-pr-required

#3011 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#3013 bpf/proxy: exclude local workloads from NodePortRemotes
  bpf/proxy/syncer.go
  fv/bpf_test.go
Labels: release-note-required, docs-pr-required, merge-when-ready, delete-branch
