Repository projectcalico/felix, pull requests merged in 2021-03, with the labels that each got.

#2691 Remove deprecated -i flag on go build
  Makefile
Labels: docs-pr-required, release-note-required

#2690 Service loop prevention for external IPs
  calc/calc_graph_test.go
  calc/event_sequencer.go
  dataplane/linux/service_loop_mgr.go
  fv/service_loop_prevention_test.go
  fv/test-connection/test-connection.go
  proto/felixbackend.pb.go
  proto/felixbackend.proto
Labels: docs-not-required, release-note-required

#2693 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2695 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2698 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2699 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2697 [v3.16] Disable Semaphore's copy-on-write docker mount.
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required

#2700 [v3.17] Backport copy-on-write fix for semaphore
  .semaphore/semaphore.yml
Labels: docs-pr-required, release-note-required

#2694 Added support for programming static rules on Windows
  dataplane/windows/policy_mgr_test.go
  dataplane/windows/policysets/policysets.go
  dataplane/windows/policysets/policysets_test.go
  dataplane/windows/policysets/static_rules.go
  dataplane/windows/policysets/static_rules_test.go
  dataplane/windows/win_dataplane.go
Labels: docs-pr-required, release-note-required

#2701 Merge pull request #2694 from song-jiang/song-static-rule
  dataplane/windows/policy_mgr_test.go
  dataplane/windows/policysets/policysets.go
  dataplane/windows/policysets/policysets_test.go
  dataplane/windows/policysets/static_rules.go
  dataplane/windows/policysets/static_rules_test.go
  dataplane/windows/win_dataplane.go
Labels: docs-pr-required, release-note-required

#2704 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2703 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2702 Added support for programming static rules on Windows
  dataplane/windows/policy_mgr_test.go
  dataplane/windows/policysets/policysets.go
  dataplane/windows/policysets/policysets_test.go
  dataplane/windows/policysets/static_rules.go
  dataplane/windows/policysets/static_rules_test.go
  dataplane/windows/win_dataplane.go
Labels: docs-pr-required, release-note-required

#2705 bpf: calculate ICMP csum as L4 not to confuse offloading
  bpf-gpl/icmp.h
Labels: docs-pr-required, release-note-required

#2646 Allow FailsafeInboundHostPorts & FailsafeOutboundHostPorts CIDRs
  config/config_params.go
  config/config_params_test.go
  config/param_types.go
  dataplane/driver.go
  rules/static.go
  rules/static_test.go
Labels: docs-pr-required, release-note-required

#2708 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2709 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2707 bpf/conntrack: scanners IterationEnd called in reverse order
  bpf/conntrack/scanner.go
Labels: docs-pr-required, release-note-required

#2710 Handle failure of netlink channel. Reconnect and resync
  daemon/daemon.go
  dataplane/driver.go
  dataplane/driver_windows.go
  dataplane/linux/int_dataplane.go
  dataplane/windows/policysets/static_rules.go
  ifacemonitor/iface_monitor.go
  ifacemonitor/ifacemonitor_test.go
  ifacemonitor/netlink_real.go
  ifacemonitor/update_filter.go
  ifacemonitor/update_filter_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-required

#2714 [v3.18] Handle failure of netlink channel. Reconnect and resync
  daemon/daemon.go
  dataplane/driver.go
  dataplane/driver_windows.go
  dataplane/linux/int_dataplane.go
  ifacemonitor/iface_monitor.go
  ifacemonitor/ifacemonitor_test.go
  ifacemonitor/netlink_real.go
  ifacemonitor/update_filter.go
  ifacemonitor/update_filter_test.go
Labels: docs-not-required, release-note-required

#2711 [v3.17] Handle failure of netlink channel. Reconnect and resync
  daemon/daemon.go
  dataplane/driver.go
  dataplane/driver_windows.go
  dataplane/linux/int_dataplane.go
  ifacemonitor/iface_monitor.go
  ifacemonitor/ifacemonitor_test.go
  ifacemonitor/netlink_real.go
  ifacemonitor/update_filter.go
  ifacemonitor/update_filter_test.go
Labels: docs-not-required, release-note-required

#2713 [v3.15] Handle failure of netlink channel. Reconnect and resync
  .semaphore/semaphore.yml
  daemon/daemon.go
  dataplane/driver.go
  dataplane/driver_windows.go
  dataplane/linux/int_dataplane.go
  fv/wireguard_test.go
  ifacemonitor/iface_monitor.go
  ifacemonitor/ifacemonitor_test.go
  ifacemonitor/netlink_real.go
  ifacemonitor/update_filter.go
  ifacemonitor/update_filter_test.go
  proto/felixbackend.pb.go
  rules/rule_defs.go
Labels: docs-not-required, release-note-required

#2712 [v3.16] Handle failure of netlink channel. Reconnect and resync
  daemon/daemon.go
  dataplane/driver.go
  dataplane/driver_windows.go
  dataplane/linux/int_dataplane.go
  ifacemonitor/iface_monitor.go
  ifacemonitor/ifacemonitor_test.go
  ifacemonitor/netlink_real.go
  ifacemonitor/update_filter.go
  ifacemonitor/update_filter_test.go
Labels: docs-not-required, release-note-required

#2675 Send SYN retries to the same backend.
  bpf-gpl/conntrack.h
  bpf/ut/nat_test.go
Labels: docs-not-required, merge-when-ready, release-note-required

#2718 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2715 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2716 Failsafe cidrs 3.18
  config/config_params.go
  config/config_params_test.go
  config/param_types.go
  dataplane/driver.go
  rules/static.go
  rules/static_test.go
Labels: docs-not-required, release-note-required

#2719 Failsafe cidrs 3.17
  config/config_params.go
  config/config_params_test.go
  config/param_types.go
  dataplane/driver.go
  rules/static.go
  rules/static_test.go
Labels: docs-not-required, release-note-required

#2722 Rev libcalico-go and kubernetes pins.
  .gitignore
  bpf/proxy/proxy.go
  bpf/ut/nat_test.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2720 Allow FailsafeInboundHostPorts and FailsafeOutboundHostPorts to be configured with an optional CIDR (format: protocol:cidr:port)
  config/config_params.go
  config/config_params_test.go
  config/param_types.go
  dataplane/driver.go
  rules/static.go
  rules/static_test.go
Labels: docs-not-required, release-note-required

#2721 Allow FailsafeInboundHostPorts and FailsafeOutboundHostPorts to be configured with an optional CIDR (format: protocol:cidr:port)
  config/config_params.go
  config/config_params_test.go
  config/param_types.go
  dataplane/driver.go
  rules/static.go
  rules/static_test.go
Labels: docs-not-required, release-note-required

#2723 [master] Semaphore Auto Pin Update
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2730 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2728 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2729 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2731 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2724 Set interface IP as source IP for ICMP replies
  bpf-gpl/bpf.h
  bpf-gpl/icmp.h
  bpf/binary.go
  bpf/tc/attach.go
  bpf/ut/attach_test.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/icmp_port_unreachable_test.go
  bpf/ut/icmp_too_big_test.go
  bpf/ut/icmp_ttl_exceeded_test.go
  bpf/ut/precompilation_test.go
  dataplane/linux/bpf_ep_mgr.go
Labels: docs-pr-required, release-note-required

#2736 bpf: set rc to TC_ACT_UNSPEC if CALI_RES_REDIR_IFINDEX fails
  bpf-gpl/fib.h
Labels: docs-pr-required, release-note-required

#2742 Add handling for IPv6 networks in failsafe rules
  config/config_params.go
  config/config_params_test.go
  config/param_types.go
  dataplane/driver.go
  rules/static.go
  rules/static_test.go
Labels: docs-pr-required, release-note-required

#2748 Add handling for IPv6 networks in failsafe rules
  config/config_params.go
  config/config_params_test.go
  config/param_types.go
  dataplane/driver.go
  rules/static.go
  rules/static_test.go
Labels: docs-not-required, release-note-required

#2749 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required
