Repository projectcalico/felix, pull requests merged in 2021-08, with the labels that each got.

#2945 ease up wireguard metrics log levels
  wireguard/metrics.go
Labels: docs-not-required, release-note-not-required

#2935 cherry-pick: "Propagate WireguardHostEncryptionEnabled config_param (#2897)"
  dataplane/driver.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/int_dataplane_test.go
  dataplane/linux/wireguard_mgr.go
  rules/rule_defs.go
  rules/static.go
  rules/static_test.go
  wireguard/config.go
  wireguard/wireguard.go
Labels: docs-not-required, release-note-not-required

#2912 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2947 update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2948 [release-v3.19] Semaphore Auto Pin Update
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2946 Update to AWS API v2.
  aws/ec2.go
  aws/ec2_test.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#2944 XDP UT and fixes to the XDP program
  bpf-gpl/Makefile
  bpf-gpl/calculate-flags
  bpf-gpl/icmp.h
  bpf-gpl/list-ut-objs
  bpf-gpl/metadata.h
  bpf-gpl/parsing.h
  bpf-gpl/skb.h
  bpf-gpl/tc.c
  bpf-gpl/xdp.c
  bpf/polprog/pol_prog_builder.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/pol_prog_test.go
  bpf/ut/xdp_test.go
Labels: docs-not-required, release-note-not-required

#2949 Align setting of BPF policy result with Enterprise code
  bpf/polprog/pol_prog_builder.go
  bpf/state/map.go
  bpf/ut/pol_prog_test.go
Labels: docs-not-required, release-note-not-required

#2950 Correction to polprog building for XDP
  bpf/polprog/pol_prog_builder.go
  bpf/ut/bpf_prog_test.go
Labels: docs-not-required, release-note-not-required

#2952 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2955 Rev netlink and fix incompatibility with new netlink library.
  dataplane/driver.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/vxlan_mgr.go
  dataplane/linux/vxlan_mgr_test.go
  go.mod
  go.sum
  routetable/route_table.go
  routetable/route_table_test.go
  wireguard/wireguard.go
  wireguard/wireguard_test.go
Labels: release-note-required, docs-pr-required, merge-when-ready

#2956 Backport from PR #2944 - Fix dest match in XDP
  bpf-gpl/parsing.h
  bpf/polprog/pol_prog_builder.go
Labels: docs-not-required, release-note-not-required

#2957 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2958 [release-v3.18] Semaphore Auto Pin Update
  .semaphore/semaphore.yml
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2959 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2960 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2961 [release-v3.20] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2962 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2965 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2964 Fix slow performance of updating a namespace.
  labelindex/named_port_bench_test.go
  labelindex/named_port_index.go
Labels: release-note-required, docs-pr-required

#2972 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2966 remove unions in cali_tc_ctx/state structure
  bpf-gpl/conntrack.h
  bpf-gpl/icmp.h
  bpf-gpl/nat.h
  bpf-gpl/parsing.h
  bpf-gpl/skb.h
  bpf-gpl/tc.c
  bpf-gpl/types.h
  bpf-gpl/xdp.c
Labels: docs-not-required, release-note-not-required

#2974 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2973 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2976 revert union in cali_tc_state
  bpf-gpl/parsing.h
  bpf-gpl/tc.c
  bpf-gpl/types.h
Labels: docs-not-required, release-note-not-required

#2975 Upgrade libbpf to v0.4.0
  bpf-gpl/include/libbpf/.travis.yml
  bpf-gpl/include/libbpf/BPF-CHECKPOINT-COMMIT
  bpf-gpl/include/libbpf/CHECKPOINT-COMMIT
  bpf-gpl/include/libbpf/LICENSE.LGPL-2.1
  bpf-gpl/include/libbpf/README.md
  bpf-gpl/include/libbpf/include/uapi/linux/bpf.h
  bpf-gpl/include/libbpf/include/uapi/linux/btf.h
  bpf-gpl/include/libbpf/include/uapi/linux/if_link.h
  bpf-gpl/include/libbpf/scripts/sync-kernel.sh
  bpf-gpl/include/libbpf/src/Makefile
  bpf-gpl/include/libbpf/src/bpf.c
  bpf-gpl/include/libbpf/src/bpf_core_read.h
  bpf-gpl/include/libbpf/src/bpf_helper_defs.h
  bpf-gpl/include/libbpf/src/bpf_helpers.h
  bpf-gpl/include/libbpf/src/bpf_tracing.h
  bpf-gpl/include/libbpf/src/btf.c
  bpf-gpl/include/libbpf/src/btf.h
  bpf-gpl/include/libbpf/src/btf_dump.c
  bpf-gpl/include/libbpf/src/hashmap.h
  bpf-gpl/include/libbpf/src/libbpf.c
  bpf-gpl/include/libbpf/src/libbpf.h
  bpf-gpl/include/libbpf/src/libbpf.map
  bpf-gpl/include/libbpf/src/libbpf_internal.h
  bpf-gpl/include/libbpf/src/libbpf_probes.c
  bpf-gpl/include/libbpf/src/libbpf_util.h
  bpf-gpl/include/libbpf/src/linker.c
  bpf-gpl/include/libbpf/src/netlink.c
  bpf-gpl/include/libbpf/src/nlattr.h
  bpf-gpl/include/libbpf/src/ringbuf.c
  bpf-gpl/include/libbpf/src/strset.c
  bpf-gpl/include/libbpf/src/strset.h
  bpf-gpl/include/libbpf/src/xsk.c
  bpf-gpl/include/libbpf/src/xsk.h
  bpf-gpl/include/libbpf/travis-ci/managers/debian.sh
  bpf-gpl/include/libbpf/travis-ci/managers/ubuntu.sh
  bpf-gpl/include/libbpf/travis-ci/vmtest/build_selftests.sh
  bpf-gpl/include/libbpf/travis-ci/vmtest/configs/blacklist/BLACKLIST-5.5.0
  bpf-gpl/include/libbpf/travis-ci/vmtest/configs/latest.config
  bpf-gpl/include/libbpf/travis-ci/vmtest/prepare_selftests-4.9.0.sh
  bpf-gpl/include/libbpf/travis-ci/vmtest/prepare_selftests-5.5.0.sh
  bpf-gpl/include/libbpf/travis-ci/vmtest/run.sh
  bpf-gpl/include/libbpf/travis-ci/vmtest/run_selftests.sh
  bpf-gpl/include/libbpf/travis-ci/vmtest/run_vmtest.sh
  bpf-gpl/include/libbpf/travis-ci/vmtest/vmlinux.h
Labels: release-note-required, docs-pr-required

#2967 Automated cherry pick of #2964: Fix slow performance of updating a namespace.
  labelindex/named_port_bench_test.go
  labelindex/named_port_index.go
Labels: release-note-required, docs-not-required

#2968 Automated cherry pick of #2964: Fix slow performance of updating a namespace.
  labelindex/named_port_bench_test.go
  labelindex/named_port_index.go
Labels: release-note-required, docs-not-required

#2866 Add test for delete/add during iteration of BPF map
  bpf/ut/maps_test.go
Labels: release-note-required, docs-pr-required

#2910 BPF mode support for general untracked policy
  bpf-gpl/bpf.h
  bpf-gpl/conntrack.h
  bpf-gpl/list-ut-objs
  bpf-gpl/tc.c
  bpf-gpl/types.h
  bpf-gpl/xdp.c
  bpf/ipsets/ipsets.go
  bpf/tc/tc_defs.go
  bpf/ut/xdp_test.go
  dataplane/driver.go
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/ipsets_mgr.go
  dataplane/linux/mock_ipsets_for_test.go
  dataplane/linux/policy_mgr.go
  dataplane/linux/policy_mgr_test.go
  dataplane/windows/ipsets/ipset_defs.go
  dataplane/windows/ipsets/ipsets.go
  fv/donottrack_test.go
  fv/wireguard_test.go
  fv/xdp_test.go
  ipsets/ipsets.go
  ipsets/ipsets_test.go
  iptables/match_builder.go
  iptables/rules.go
  rules/endpoints.go
  rules/rule_defs.go
  rules/static.go
Labels: release-note-required, docs-pr-required

#2978 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2969 Automated cherry pick of #2964: Fix slow performance of updating a namespace.
  .semaphore/collect-artifacts
  .semaphore/collect-artifacts-from-vms
  .semaphore/create-test-vm
  .semaphore/create-test-vms
  .semaphore/new-kernel-common.sh
  .semaphore/run-tests-on-vms
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
  labelindex/named_port_bench_test.go
  labelindex/named_port_index.go
Labels: release-note-required, docs-not-required

#2970 Automated cherry pick of #2964: Fix slow performance of updating a namespace.
  .semaphore/collect-artifacts
  .semaphore/collect-artifacts-from-vms
  .semaphore/create-test-vm
  .semaphore/create-test-vms
  .semaphore/new-kernel-common.sh
  .semaphore/run-tests-on-vms
  .semaphore/semaphore.yml
  .semaphore/update_pins.yml
  Makefile
  labelindex/named_port_bench_test.go
  labelindex/named_port_index.go
Labels: release-note-required, docs-not-required

#2971 Automated cherry pick of #2964: Fix slow performance of updating a namespace.
  .semaphore/collect-artifacts
  .semaphore/collect-artifacts-from-vms
  .semaphore/create-test-vm
  .semaphore/create-test-vms
  .semaphore/new-kernel-common.sh
  .semaphore/run-tests-on-vms
  .semaphore/semaphore.yml
  Makefile
  labelindex/named_port_bench_test.go
  labelindex/named_port_index.go
Labels: release-note-required, docs-not-required

#2979 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#2980 Abolish BPF mode's fixed Calico mark pattern
  bpf-gpl/bpf.h
  bpf-gpl/list-ut-objs
  bpf/tc/tc_defs.go
Labels: docs-not-required, release-note-not-required

#2981 Move IP sets manager to common location
  dataplane/common/callbacks.go
  dataplane/common/ipsets_mgr.go
  dataplane/common/ipsets_mgr_test.go
  dataplane/common/mock_ipsets.go
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/endpoint_mgr_test.go
  dataplane/linux/hostip_mgr.go
  dataplane/linux/hostip_mgr_test.go
  dataplane/linux/int_dataplane.go
  dataplane/linux/ipip_mgr.go
  dataplane/linux/ipip_mgr_test.go
  dataplane/linux/ipsets_mgr_test.go
  dataplane/linux/masq_mgr.go
  dataplane/linux/masq_mgr_test.go
  dataplane/linux/sockmap_state.go
  dataplane/linux/vxlan_mgr.go
  dataplane/linux/vxlan_mgr_test.go
  dataplane/linux/xdp_state.go
  dataplane/windows/endpoint_mgr.go
  dataplane/windows/ipsets/ipset_defs.go
  dataplane/windows/ipsets/ipsets.go
  dataplane/windows/ipsets_mgr.go
  dataplane/windows/ipsets_mgr_test.go
  dataplane/windows/policysets/policysets_test.go
  dataplane/windows/win_dataplane.go
Labels: docs-not-required, release-note-not-required

#2982 Drop a half-untracked flow at HEP egress
  bpf-gpl/tc.c
Labels: release-note-required, docs-pr-required

#2987 bpf/ut: withXDP()
  bpf/ut/benchmarks_test.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/failsafes_test.go
  bpf/ut/icmp_port_unreachable_test.go
  bpf/ut/icmp_related_test.go
  bpf/ut/icmp_ttl_exceeded_test.go
  bpf/ut/ip_options_test.go
  bpf/ut/nat_test.go
  bpf/ut/spoof_test.go
  bpf/ut/to_host_allowed_test.go
  bpf/ut/whitelist_test.go
  bpf/ut/xdp_test.go
Labels: release-note-required, docs-pr-required

#2984 [master] Semaphore Auto Pin Update
  fv/named_ports_test.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required
