Repository projectcalico/felix, pull requests merged in 2021-10, with the labels that each got.

#2963 Load TC programs using libbpf
  Makefile
  bpf-gpl/Makefile
  bpf-gpl/bpf.h
  bpf-gpl/calculate-flags
  bpf-gpl/jump.h
  bpf-gpl/policy.h
  bpf-gpl/policy_program.h
  bpf-gpl/tc.c
  bpf/bpf_syscall.go
  bpf/libbpf/libbpf.go
  bpf/libbpf/libbpf_api.h
  bpf/libbpf/libbpf_stub.go
  bpf/tc/attach.go
  bpf/tc/compiler.go
  bpf/ut/attach_test.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/precompilation_test.go
  bpf/xdp/attach.go
  dataplane/linux/bpf_ep_mgr.go
  fv/bpf_test.go
Labels: release-note-required, docs-pr-required

#3017 bpf/proxy: program only Ready endpoints in NAT
  bpf/proxy/syncer.go
  bpf/proxy/syncer_test.go
Labels: release-note-required, docs-pr-required

#3018 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#3015 bpf/proxy: fix conn cleaning when ExternalTrafficPolicy=Local
  bpf/proxy/syncer.go
  bpf/proxy/syncer_test.go
Labels: release-note-required, docs-pr-required

#3019 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#3021 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#3016 Replace hyperkube, update k8s version
  Makefile
  fv/bpf_test.go
  fv/certs/README.md
  fv/certs/admin-csr.json
  fv/certs/admin-key.pem
  fv/certs/admin.csr
  fv/certs/admin.pem
  fv/certs/ca-config.json
  fv/certs/ca-csr.json
  fv/certs/ca-key.pem
  fv/certs/ca.csr
  fv/certs/ca.pem
  fv/certs/kube-controller-manager.kubeconfig
  fv/certs/kubeconfig
  fv/certs/kubernetes-csr.json
  fv/certs/kubernetes-key.pem
  fv/certs/kubernetes.csr
  fv/certs/kubernetes.pem
  fv/certs/service-account-csr.json
  fv/certs/service-account-key.pem
  fv/certs/service-account.csr
  fv/certs/service-account.pem
  fv/infrastructure/infra_k8s.go
  k8sfv/run-test
Labels: docs-not-required, release-note-not-required

#3022 [master] Semaphore Auto Pin Update
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch
