Repository projectcalico/felix, pull requests merged in 2021-11, with the labels that each got.

#3060 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#3061 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#3057 Only collect WireGuard prom stats when enabled (#3052)
  dataplane/driver.go
  go.mod
  go.sum
  wireguard/metrics.go
Labels: release-note-required, docs-not-required

#3058 Only collect WireGuard prom stats when enabled
  dataplane/driver.go
  go.mod
  go.sum
  wireguard/metrics.go
Labels: release-note-required, docs-not-required

#3055 Fix Windows FV test assertion
  dataplane/windows/ipsets/ipset_defs.go
  dataplane/windows/ipsets/ipsets.go
  fv/winfv/policy_test.go
Labels: docs-not-required, release-note-not-required, merge-when-ready

#3063 Automated cherry pick of #3055: Fix Windows FV test assertion
  dataplane/windows/ipsets/ipset_defs.go
  dataplane/windows/ipsets/ipsets.go
  fv/winfv/policy_test.go
Labels: docs-not-required, release-note-not-required

#3064 [release-v3.20] Semaphore Auto Pin Update
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#3066 Manually update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#3059 Load CTLB using libbpf
  bpf-gpl/calculate-flags
  bpf-gpl/connect_balancer.c
  bpf-gpl/connect_balancer_v6.c
  bpf/libbpf/libbpf.go
  bpf/libbpf/libbpf_api.h
  bpf/libbpf/libbpf_stub.go
  bpf/nat/connecttime.go
  bpf/tc/attach.go
  dataplane/linux/int_dataplane.go
Labels: release-note-required, docs-pr-required

#3002 Avoid reattaching BPF programs after restart if they haven't changed
  bpf/attach.go
  bpf/bpf_defs.go
  bpf/tc/attach.go
  bpf/ut/attach_test.go
  bpf/xdp/attach.go
  dataplane/linux/bpf_ep_mgr.go
  fv/bpf_attach_test.go
  fv/policysync_test.go
Labels: docs-not-required, release-note-not-required

#3068 Dual license the BPF part of the codebase as Apache/GPL.
  bpf-gpl/LICENSE.Apache
  bpf-gpl/LICENSE.GPLv2
  bpf-gpl/Makefile
  bpf-gpl/README
  bpf-gpl/arp.h
  bpf-gpl/bpf.h
  bpf-gpl/calculate-flags
  bpf-gpl/connect_balancer.c
  bpf-gpl/connect_balancer_v6.c
  bpf-gpl/conntrack.h
  bpf-gpl/conntrack_types.h
  bpf-gpl/failsafe.h
  bpf-gpl/fib.h
  bpf-gpl/globals.h
  bpf-gpl/icmp.h
  bpf-gpl/jump.h
  bpf-gpl/list-objs
  bpf-gpl/list-ut-objs
  bpf-gpl/log.h
  bpf-gpl/metadata.h
  bpf-gpl/nat.h
  bpf-gpl/nat_types.h
  bpf-gpl/parsing.h
  bpf-gpl/policy.h
  bpf-gpl/policy_program.h
  bpf-gpl/reasons.h
  bpf-gpl/routes.h
  bpf-gpl/sendrecv.h
  bpf-gpl/skb.h
  bpf-gpl/tc.c
  bpf-gpl/tc.h
  bpf-gpl/types.h
  bpf-gpl/ut/icmp_port_unreachable.c
  bpf-gpl/ut/icmp_too_big.c
  bpf-gpl/ut/icmp_ttl_exceeded.c
  bpf-gpl/ut/ip_dec_ttl.c
  bpf-gpl/ut/nat_decap_test.c
  bpf-gpl/ut/nat_encap_test.c
  bpf-gpl/ut/ut.h
  bpf-gpl/xdp.c
  git-hooks/pre-commit-in-container
Labels: release-note-required, docs-pr-required, merge-when-ready

#3070 bpf/fv: affinity cleaned up after service/backend gone
  bpf-gpl/nat.h
  fv/bpf_test.go
Labels: release-note-required, docs-pr-required

#3067 bpf: enforce affinity for unconnected UDP with CTLB
  bpf-gpl/connect_balancer.c
  bpf-gpl/nat.h
  fv/bpf_test.go
Labels: release-note-required, docs-pr-required

#3071 Ubuntu packaging: add Build-Depend on libelf-dev
  debian/control
Labels: docs-not-required, release-note-not-required

#3074 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#3069 bpf/ctlb: fail connect if there is no backend
  bpf-gpl/connect_balancer.c
  fv/bpf_test.go
Labels: release-note-required, docs-not-required

#3073 bpf: reattach programs when their configuration changes
  bpf/attach.go
  bpf/tc/attach.go
  bpf/ut/attach_test.go
  bpf/xdp/attach.go
  fv/bpf_attach_test.go
Labels: release-note-required, docs-not-required

#3078 Squash some spammy logs
  wireguard/wireguard.go
Labels: release-note-required, docs-not-required, merge-when-ready

#3079 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#3080 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#3081 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#3082 [release-v3.19] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#3084 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#3086 Update pins
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#3087 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#3077 bpf: CTLB configurable udp_not_seen_timeo
  bpf-gpl/bpf.h
  bpf-gpl/connect_balancer.c
  bpf-gpl/globals.h
  bpf-gpl/nat.h
  bpf-gpl/nat_lookup.h
  bpf-gpl/tc.c
  bpf/libbpf/libbpf.go
  bpf/libbpf/libbpf_api.h
  bpf/libbpf/libbpf_stub.go
  bpf/nat/connecttime.go
  dataplane/linux/int_dataplane.go
Labels: release-note-required, docs-not-required

#3072 Update windows fv
  bpf-gpl/nat_lookup.h
  fv/winfv/policy_test.go
Labels: release-note-required, docs-pr-required

#3076 bpf: fix ExternalTrafficPolicy=Local
  bpf-gpl/connect_balancer.c
  bpf-gpl/nat_lookup.h
  bpf-gpl/nat_types.h
  bpf/nat/maps.go
  bpf/proxy/kube-proxy.go
  bpf/proxy/syncer.go
  bpf/proxy/syncer_test.go
  cmd/calico-bpf/commands/nat.go
  fv/bpf_test.go
  go.mod
Labels: release-note-required, docs-not-required

#3004 Experiment - Publish test results
  .semaphore/semaphore.yml
Labels: docs-not-required, release-note-not-required
