Repository projectcalico/felix, pull requests merged in 2021-12, with the labels that each got.

#3089 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#3091 [release-v3.21] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required, merge-when-ready, delete-branch

#3088 Write the name of the policy into iptables as a comment.
  fv/ingress_egress_test.go
  iptables/rules.go
  rules/policy.go
  rules/policy_test.go
Labels: release-note-required, docs-not-required, merge-when-ready

#3094 Fix duplicate type static check
  bpf/ut/bpf_prog_test.go
Labels: docs-not-required, release-note-not-required

#3093 Add LogDebugFilenameRegex to control debug logging.
  config/config_params.go
  config/config_params_test.go
  config/param_types.go
  go.mod
  go.sum
  logutils/logutils.go
Labels: release-note-required, docs-pr-required, merge-when-ready

#3095 Fix wireguard bpf failure
  bpf/tc/attach.go
Labels: release-note-required, docs-pr-required

#3097 Update gomega -> v1.15.0
  Makefile
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required

#3098 Update to gomega v1.15.0
  Makefile
  bpf/ut/bpf_prog_test.go
  go.mod
  go.sum
Labels: docs-not-required, release-note-not-required
