Repository projectcalico/felix, pull requests merged in 2021-02, with the labels that each got.

#2665 BPF: upstreaming general improvements made as part of Enterprise PR for DNS policy work
  Makefile
  bpf-gpl/bpf.h
  bpf-gpl/conntrack.h
  bpf-gpl/conntrack_types.h
  bpf-gpl/jump.h
  bpf-gpl/tc.c
  bpf-gpl/types.h
  bpf/state/map.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/pol_prog_test.go
  fv/containers/containers.go
  fv/test-connection/test-connection.go
  fv/utils/utils.go
  fv/workload/workload.go
Labels: docs-not-required, release-note-not-required

#2667 UT for BPF-mode host endpoint policy
  bpf/ut/pol_prog_test.go
  dataplane/linux/bpf_ep_mgr.go
  dataplane/linux/bpf_ep_mgr_test.go
  dataplane/linux/endpoint_mgr.go
  dataplane/linux/endpoint_mgr_test.go
Labels: docs-not-required, release-note-not-required

#2666 Add support for generic IP protocols.
  bpf-gpl/conntrack.h
  bpf-gpl/tc.c
  bpf/conntrack/cleanup.go
  bpf/conntrack/conntrack_test.go
  bpf/polprog/pol_prog_builder.go
  bpf/ut/bpf_prog_test.go
  bpf/ut/pol_prog_test.go
  fv/connectivity/conncheck.go
  fv/fv_infra_test.go
  fv/hostendpoints_test.go
  fv/test-connection/test-connection.go
  fv/test-workload/test-workload.go
  fv/workload/workload.go
Labels: docs-not-required, merge-when-ready, release-note-required

#2668 [release-v3.17] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2669 In BPF mode, enable the FIB lookup when VXLAN is enabled.
  dataplane/linux/int_dataplane.go
Labels: docs-pr-required, release-note-required

#2670 Group dataplane code together at the end of bpf_ep_mgr.go
  dataplane/linux/bpf_ep_mgr.go
  dataplane/linux/bpf_ep_mgr_test.go
Labels: docs-not-required, release-note-not-required

#2671 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2672 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2676 Do not forward incoming VXLAN packets.
  bpf-gpl/tc.c
Labels: docs-not-required, merge-when-ready, release-note-not-required

#2677 Do not forward incoming VXLAN packets.
  bpf-gpl/tc.c
Labels: docs-not-required, release-note-not-required

#2678 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2679 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2680 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2681 [release-v3.18] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2682 Ignore log rules in BPF mode.
  bpf/polprog/pol_prog_builder.go
  bpf/polprog/pol_prog_builder_test.go
  bpf/ut/pol_prog_test.go
Labels: docs-pr-required, merge-when-ready, release-note-required

#2684 [v3.18] Ignore log rules in BPF mode.
  bpf/polprog/pol_prog_builder.go
  bpf/polprog/pol_prog_builder_test.go
  bpf/ut/pol_prog_test.go
Labels: docs-pr-required, release-note-required

#2685 [master] Semaphore Auto Pin Update
  go.mod
  go.sum
Labels: delete-branch, docs-not-required, merge-when-ready, release-note-not-required

#2683 [v3.17] ignore log rules in eBPF mode
  bpf/polprog/pol_prog_builder.go
  bpf/polprog/pol_prog_builder_test.go
  bpf/ut/pol_prog_test.go
Labels: docs-not-required, release-note-required

#2688 Allow felix build on 32 bits systems (armv7)
  bpf/tc/tc_defs.go
Labels: docs-not-required, merge-when-ready, release-note-not-required

#2689 Fix that VXLAN tests only ever tested the WorkloadIP case.
  fv/vxlan_test.go
Labels: cherry-pick-candidate, docs-not-required, release-note-not-required

#2686 For eBPF data plane, respect externalTrafficPolicy for LB services
  bpf/proxy/syncer.go
Labels: docs-pr-required, release-note-required
